// tools/cases/patterns.mjs … 転職パターンの定義（40種）。
//
// 1パターン＝「どこから、どこへ」の1本の線。事例はこの線の上に25件ずつ並ぶ。
//
// ⚠ 実在の企業名は書かない。企業は必ず「大手SIer」「シリーズBのSaaS」のような
//   類型で表す。特定の会社の選考について述べた記述と読まれる余地を残さないため。
//
// question … その事例集が答えようとしている、求職者側の問いの形。
//            パターンページの h2 とJSON-LDのFAQに使う。

import { PATTERNS_EXTRA, AREAS_EXTRA } from './patterns-extra.mjs';

const AREAS_CORE = {
  consul: { label: 'コンサルティング', note: '未経験からの入社、ファーム間の移動、ファームから事業会社への移動まで。' },
  ma: { label: 'M&A・FAS', note: '仲介・FA・FAS・事業会社のM&A部門。同じ「M&A」でも役割は大きく違う。' },
  pm: { label: 'PM・PdM・PMO', note: '受託のプロジェクトマネジメントから、事業会社・SaaSのプロダクト側への移動。' },
  eng: { label: 'エンジニア・IT', note: 'SIer／SESから事業会社へ、運用から設計へ、組込みからプロダクトへ。' },
  biz: { label: '事業開発・経営企画', note: 'スタートアップの事業側、経営企画、コーポレート部門への移動。' },
};

const P = (o) => o;

const PATTERNS_CORE = [
  /* ================= コンサルティング ================= */
  P({
    slug: 'sier-se-to-it-consultant', area: 'consul',
    label: '大手SIerのSE → ITコンサルタント',
    question: '大手SIerのSEからITコンサルタントに転職できますか。何が評価されて、何が足りないと見られますか。',
    lead: '最も件数が多い移動の一つ。工程が上流に寄るだけに見えて、実際に変わるのは「誰の課題を解くか」。ベンダー側では与件だった前提を、自分で置く側に回る点が評価の分かれ目になる。',
    before: { industry: 'SIer・システムインテグレーション', companies: ['大手SIer（メーカー系）', '大手SIer（ユーザー系）', '大手SIer（独立系）', '大手通信系SIer'], roles: ['システムエンジニア', 'アプリケーションエンジニア', '業務システムのSE', 'インフラSE'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', '外資系コンサルティングファーム（総合）', 'IT系コンサルティングファーム', '国内独立系コンサルティングファーム'], roles: ['ITコンサルタント', 'テクノロジーコンサルタント', 'シニアコンサルタント'] },
    age: [26, 36], income: [480, 780], delta: [30, 220],
    motives: ['upstream', 'skill', 'income', 'scope'], barriers: ['vendorside', 'nonum', 'bigco'], breaks: ['reframe', 'casestudy', 'number', 'narrow'],
    incomeLogic: ['up_scope', 'up_scarcity', 'up_role'], takeaways: ['reframe', 'bridge'],
    tags: ['未経験からコンサル', 'SIer出身', 'ケース面接'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。担当していたのは基幹システムの改修と保守が中心で、要件定義の場に同席することはあっても、要件を決めるのは顧客側という前提は動かなかった。`,
      (c) => `${c.beforeCompany}に新卒で入り、${c.years}年目。大規模プロジェクトの一部工程を任される立場で、品質と納期の管理には自信があった。一方で、そのシステムが顧客の事業にどう効いたのかを確かめる機会はなかった。`,
    ],
  }),
  P({
    slug: 'jigyou-kikaku-to-strategy-consul', area: 'consul',
    label: '事業会社の経営企画 → 戦略コンサルタント',
    question: '事業会社の経営企画から戦略コンサルに転職するのは可能ですか。年齢の上限はありますか。',
    lead: '事業側で「考える仕事」をしてきた人の移動。分析の型は持っていることが多い一方で、事業会社のスピード感で許容されていた粗さが選考で論点になる。',
    before: { industry: '事業会社', companies: ['東証プライム上場のメーカー', '大手小売企業', '大手サービス業', '上場企業の事業会社'], roles: ['経営企画', '事業企画', '経営管理', '事業戦略担当'] },
    after: { industry: 'コンサルティング', companies: ['戦略系コンサルティングファーム', '外資系戦略ファーム', '総合系ファームの戦略部門'], roles: ['コンサルタント', 'アソシエイト', 'シニアアソシエイト'] },
    age: [26, 34], income: [550, 850], delta: [50, 350],
    motives: ['skill', 'speed', 'scope'], barriers: ['agefit', 'nonum', 'bigco'], breaks: ['casestudy', 'number', 'reframe'],
    incomeLogic: ['up_scope', 'up_role', 'up_negotiation'], takeaways: ['timing', 'reframe'],
    tags: ['未経験からコンサル', '戦略ファーム', 'ケース面接'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。中期計画の策定と予実の管理が主な業務で、社内では若手の中核として扱われていた。ただ、決めているのは役員であり、自分は材料を作る側だという自覚もあった。`,
      (c) => `新卒から${c.beforeCompany}に在籍し、${c.years}年目で${c.beforeRole}へ。全社の投資判断に関わる資料を任される一方で、判断そのものの筋の良し悪しを評価される機会はなかった。`,
    ],
  }),
  P({
    slug: 'bank-sales-to-consul', area: 'consul',
    label: '銀行・証券の法人営業 → 総合系コンサルタント',
    question: '銀行の法人営業からコンサルに転職できますか。金融出身は不利ですか。',
    lead: '金融の法人営業は、経営層と話した経験と財務の読解力を持っている点が評価される。一方で「関係性で仕事を取ってきた人」と見られると、論理面での確認が厳しくなる。',
    before: { industry: '銀行・証券', companies: ['メガバンク', '大手地方銀行', '大手証券会社', '信託銀行'], roles: ['法人営業', 'RM（リレーションシップマネージャー）', '事業性評価担当', '法人ソリューション営業'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', '外資系コンサルティングファーム（総合）', '国内独立系コンサルティングファーム'], roles: ['コンサルタント', 'ビジネスコンサルタント', 'シニアコンサルタント'] },
    age: [26, 35], income: [550, 900], delta: [-30, 250],
    motives: ['skill', 'scope', 'domain'], barriers: ['nonum', 'agefit', 'industrygap'], breaks: ['casestudy', 'domainbridge', 'reframe'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_domain'], takeaways: ['bridge', 'reframe'],
    tags: ['未経験からコンサル', '金融出身', 'ケース面接'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}を${c.years}年。担当先は中堅企業が中心で、決算書を読み込んで融資と本業支援の提案をしてきた。経営者と直接話す機会は多かったが、提案の中身は自社商品の枠を出なかった。`,
      (c) => `${c.beforeCompany}に${c.years}年在籍。ノルマの達成は続けていたものの、提案できる打ち手が金融商品に限られることに物足りなさがあった。顧客の課題そのものを解く側に回りたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'maker-engineer-to-consul', area: 'consul',
    label: 'メーカーの技術職 → 製造業向けコンサルタント',
    question: 'メーカーの技術者からコンサルに転職できますか。技術の経験は評価されますか。',
    lead: '製造現場を知っている人材はファーム側で慢性的に不足している。技術の深さより、現場の制約を踏まえて意思決定した経験が評価される。',
    before: { industry: 'メーカー', companies: ['大手電機メーカー', '大手自動車メーカー', '大手部品メーカー', '大手化学メーカー'], roles: ['生産技術', '品質保証', '設計開発', '生産管理'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', '製造業特化のコンサルティングファーム', '外資系コンサルティングファーム（総合）'], roles: ['コンサルタント', 'SCMコンサルタント', 'オペレーションコンサルタント'] },
    age: [27, 38], income: [500, 800], delta: [50, 280],
    motives: ['skill', 'upstream', 'income'], barriers: ['nonum', 'bigco', 'industrygap'], breaks: ['domainbridge', 'number', 'casestudy'],
    incomeLogic: ['up_domain', 'up_scarcity', 'up_scope'], takeaways: ['bridge', 'income'],
    tags: ['未経験からコンサル', 'メーカー出身', '製造業'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。工場の現場改善から新工程の立ち上げまで担当してきた。改善の効果は数字で出ていたが、その効果が全社の損益にどう効いたかまでは追っていなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年、${c.beforeRole}に従事。海外拠点の立ち上げにも関わり、現場を動かす難しさは体で理解していた。一方で、仕事の範囲は与えられた工程の中に閉じていた。`,
    ],
  }),
  P({
    slug: 'consul-to-bigger-firm', area: 'consul',
    label: '中堅ファーム → 大手・外資系ファーム',
    question: '中堅のコンサルファームから大手や外資系ファームに移れますか。何が見られますか。',
    lead: 'ファーム間の移動では、在籍年数ではなく「どの規模の案件で、どこまで任されたか」で等級が決まる。同じタイトルでも中身が違うため、案件の粒度を説明できるかが分かれ目になる。',
    before: { industry: 'コンサルティング', companies: ['国内独立系コンサルティングファーム', '中堅の総合系ファーム', 'IT系コンサルティングファーム'], roles: ['コンサルタント', 'シニアコンサルタント', 'マネージャー'] },
    after: { industry: 'コンサルティング', companies: ['外資系コンサルティングファーム（総合）', '大手総合系コンサルティングファーム', '外資系戦略ファーム'], roles: ['シニアコンサルタント', 'マネージャー', 'シニアマネージャー'] },
    age: [28, 40], income: [700, 1200], delta: [50, 350],
    motives: ['scope', 'income', 'domain'], barriers: ['nonum', 'english', 'agefit'], breaks: ['number', 'reframe', 'narrow'],
    incomeLogic: ['up_role', 'up_scope', 'up_negotiation'], takeaways: ['income', 'reframe'],
    tags: ['ファーム間転職', '外資系', 'マネージャー'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。案件は途切れず、評価も安定していた。ただ、扱う案件の規模が頭打ちで、より大きな意思決定に関わる経験が積めない状態が続いていた。`,
      (c) => `${c.years}年在籍した${c.beforeCompany}で${c.beforeRole}まで昇進。若手の育成も任される立場になった一方で、自分自身が学べる量は年々減っていた。`,
    ],
  }),
  P({
    slug: 'sier-pmo-to-firm-pmo', area: 'consul',
    label: 'SIerのPMO → ファームのPMO・PMOコンサルタント',
    question: 'SIerのPMOからコンサルファームのPMOに移れますか。「調整役」と見られないためには？',
    lead: '同じPMOでも、ベンダー側のPMOは進捗と課題の管理、ファーム側のPMOは意思決定の設計に寄る。ここを取り違えたまま応募すると評価が伸びない。',
    before: { industry: 'SIer・システムインテグレーション', companies: ['大手SIer（メーカー系）', '大手SIer（独立系）', '大手通信系SIer'], roles: ['PMO', 'プロジェクト管理', 'PMOリーダー'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', 'IT系コンサルティングファーム', '外資系コンサルティングファーム（総合）'], roles: ['PMOコンサルタント', 'シニアコンサルタント', 'マネージャー'] },
    age: [28, 40], income: [550, 900], delta: [30, 250],
    motives: ['upstream', 'scope', 'income'], barriers: ['coordinator', 'nonum', 'vendorside'], breaks: ['reframe', 'number', 'firstline'],
    incomeLogic: ['up_scope', 'up_role', 'up_scarcity'], takeaways: ['reframe', 'evidence'],
    tags: ['PMO', 'SIer出身', '職務経歴書'],
    situations: [
      (c) => `${c.beforeCompany}で全社横断のプロジェクトのPMOを${c.years}年。数十人規模の体制の進捗と課題を管理し、関係部署との調整を担ってきた。役割としては中核だったが、それを説明する言葉を持っていなかった。`,
      (c) => `${c.beforeCompany}の${c.beforeRole}として、複数ベンダーが入る案件の統制を${c.years}年担当。火消しの依頼が集まる立場だったが、評価は「上手く回す人」で止まっていた。`,
    ],
  }),
  P({
    slug: 'public-to-publicsector-consul', area: 'consul',
    label: '官公庁・自治体 → パブリックセクターのコンサルタント',
    question: '公務員からコンサルに転職できますか。民間経験がないことは不利ですか。',
    lead: '行政の意思決定プロセスを内側から知っている人材は、パブリックセクター案件で希少。民間の速度に馴染めるかが最大の確認点になる。',
    before: { industry: '官公庁・自治体', companies: ['中央省庁', '都道府県庁', '政令指定都市の自治体', '独立行政法人'], roles: ['行政職', '政策企画', '財政・予算担当', '情報システム担当'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', 'シンクタンク系コンサルティングファーム', '公共部門特化のコンサルティングファーム'], roles: ['パブリックセクターコンサルタント', 'コンサルタント', 'シニアコンサルタント'] },
    age: [27, 42], income: [450, 750], delta: [30, 300],
    motives: ['speed', 'income', 'skill'], barriers: ['industrygap', 'nonum', 'agefit'], breaks: ['domainbridge', 'casestudy', 'study'],
    incomeLogic: ['up_domain', 'up_scarcity', 'up_scope'], takeaways: ['bridge', 'income'],
    tags: ['公務員から転職', 'パブリックセクター', '未経験からコンサル'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。制度設計と予算の折衝を担当し、庁内外の合意形成に多くの時間を使ってきた。仕事の意義は感じていたが、意思決定までの時間の長さに疲れも出ていた。`,
      (c) => `${c.years}年間、${c.beforeCompany}の${c.beforeRole}。デジタル化の推進を任されたが、調達の仕組みと人員の制約で進まない場面が続いた。外から関わるほうが早いのではないかと考え始めた。`,
    ],
  }),
  P({
    slug: 'consul-to-jigyou-keiei', area: 'consul',
    label: 'コンサルファーム → 事業会社の経営企画（ポストコンサル）',
    question: 'コンサルから事業会社に移るとき、年収は下がりますか。どんなポジションが現実的ですか。',
    lead: 'ファーム出身者の受け皿は広い一方で、報酬水準はファームより低いことが多い。何を得るために何を手放すかを決めているかどうかで、選考の進み方が変わる。',
    before: { industry: 'コンサルティング', companies: ['外資系コンサルティングファーム（総合）', '大手総合系コンサルティングファーム', '戦略系コンサルティングファーム'], roles: ['シニアコンサルタント', 'マネージャー', 'コンサルタント'] },
    after: { industry: '事業会社', companies: ['東証プライム上場企業', '上場SaaS企業', '大手事業会社', '成長企業（上場準備中）'], roles: ['経営企画', '事業企画マネージャー', '経営企画マネージャー', '事業開発'] },
    age: [28, 45], income: [800, 1500], delta: [-250, 120],
    motives: ['product', 'work', 'people', 'domain'], barriers: ['overqual', 'nonum', 'industrygap'], breaks: ['narrow', 'negotiate', 'reframe'],
    incomeLogic: ['flat_tradeoff', 'down_then_up', 'up_role'], takeaways: ['tradeoff', 'income'],
    tags: ['ポストコンサル', '経営企画', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。提案から実行支援まで一通り経験したが、案件が終われば離れる立場であることに変わりはなかった。自分が関わったものを最後まで見届けたいという気持ちが強くなった。`,
      (c) => `${c.years}年目で${c.beforeRole}。稼働の重さは覚悟の上だったが、${c.age}歳を迎えて働き方を含めた次の10年を考えるようになった。事業側で腰を据える選択肢を検討し始めた。`,
    ],
  }),

  /* ================= M&A・FAS ================= */
  P({
    slug: 'bank-to-ma-boutique', area: 'ma',
    label: '銀行・証券の法人営業 → M&A仲介・FA',
    question: '銀行からM&A仲介に転職するのはどうですか。何が違って、何が活きますか。',
    lead: '案件を「探す」局面での強さがそのまま活きる移動。一方で、成約するまで報酬が立たない構造への適応が最大の論点になる。',
    before: { industry: '銀行・証券', companies: ['メガバンク', '大手地方銀行', '大手証券会社', '信用金庫'], roles: ['法人営業', 'RM（リレーションシップマネージャー）', '事業承継担当', 'リテール営業'] },
    after: { industry: 'M&A', companies: ['M&A仲介会社（上場）', 'M&Aブティック', '独立系FA', '中堅M&A仲介会社'], roles: ['M&Aアドバイザー', 'M&Aコンサルタント', 'FA（ファイナンシャルアドバイザー）'] },
    age: [26, 40], income: [500, 900], delta: [-50, 400],
    motives: ['income', 'scope', 'skill'], barriers: ['nonum', 'agefit', 'industrygap'], breaks: ['domainbridge', 'number', 'narrow'],
    incomeLogic: ['up_stage', 'up_domain', 'up_scope'], takeaways: ['income', 'bridge'],
    tags: ['M&A仲介', '金融出身', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}を${c.years}年。担当エリアの中堅企業を回る中で、後継者不在の相談を受けることが増えていた。ただ、自行で提供できる解決策は限られていた。`,
      (c) => `${c.beforeCompany}に${c.years}年。事業承継の相談を持ちかけられても、提携先へ取り次ぐところまでしかできなかった。自分で案件を最後まで見たいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'audit-to-fas', area: 'ma',
    label: '監査法人の会計士 → FAS（財務DD・バリュエーション）',
    question: '監査法人からFASに移るとどう変わりますか。会計士の資格はどこまで効きますか。',
    lead: '会計知識は前提として扱われ、評価されるのは「不確実な情報のまま結論を出す力」。監査の網羅性の作法が、そのままでは通用しない場面が出てくる。',
    before: { industry: '監査法人', companies: ['大手監査法人', '準大手監査法人', '中堅監査法人'], roles: ['会計監査', 'シニアスタッフ', 'マネージャー'] },
    after: { industry: 'M&A・FAS', companies: ['FAS（大手系）', '独立系FAS', 'コンサルティングファームのトランザクション部門'], roles: ['財務DD担当', 'バリュエーション担当', 'トランザクションアドバイザリー', 'FASコンサルタント'] },
    age: [26, 38], income: [600, 1000], delta: [30, 300],
    motives: ['skill', 'scope', 'income'], barriers: ['nonum', 'nomanage', 'english'], breaks: ['reframe', 'study', 'number'],
    incomeLogic: ['up_scope', 'up_role', 'up_scarcity'], takeaways: ['reframe', 'income'],
    tags: ['FAS', '会計士', 'デューデリジェンス'],
    situations: [
      (c) => `${c.beforeCompany}で${c.years}年、${c.beforeRole}として上場企業の監査に従事。手続きの精度には自信があったが、過去の数字を確かめる仕事が続くことに物足りなさを感じていた。`,
      (c) => `${c.beforeCompany}に${c.years}年在籍。${c.beforeRole}として複数のクライアントを担当したが、経営の意思決定そのものに関わる機会はなかった。将来の数字を扱う側に移りたいと考えた。`,
    ],
  }),
  P({
    slug: 'consul-to-fas', area: 'ma',
    label: 'コンサルタント → FAS・ディール周辺',
    question: 'コンサルからFASやM&Aの領域に移れますか。財務の経験がなくても大丈夫ですか。',
    lead: 'ビジネスDDやPMIから入る移動が現実的。財務モデリングの経験を求められる求人と、事業の目利きを求められる求人が混在しているため、どちらの求人かを見分けることが先になる。',
    before: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', '戦略系コンサルティングファーム', 'IT系コンサルティングファーム'], roles: ['コンサルタント', 'シニアコンサルタント', 'マネージャー'] },
    after: { industry: 'M&A・FAS', companies: ['FAS（大手系）', '独立系FAS', 'PEファンドの投資先支援部門', 'コンサルティングファームのディール部門'], roles: ['ビジネスDD担当', 'PMIコンサルタント', 'トランザクションアドバイザリー'] },
    age: [27, 40], income: [700, 1200], delta: [30, 300],
    motives: ['domain', 'income', 'skill'], barriers: ['industrygap', 'nonum', 'english'], breaks: ['study', 'domainbridge', 'narrow'],
    incomeLogic: ['up_scope', 'up_scarcity', 'up_role'], takeaways: ['bridge', 'income'],
    tags: ['FAS', 'PMI', 'ファーム間転職'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。戦略の立案までは関わるが、実際に資本が動く場面には立ち会えなかった。意思決定の結果が数字として跳ね返る領域に移りたかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。PMI案件に途中から参画した経験があり、ディールの前段からの関与に興味を持った。`,
    ],
  }),
  P({
    slug: 'ma-to-jigyou-ma', area: 'ma',
    label: 'M&A仲介・FA → 事業会社のM&A・経営企画',
    question: 'M&A仲介から事業会社のM&A部門に移れますか。年収は下がりますか。',
    lead: '売る側から買う側へ。案件数は激減する代わりに、1件を長く見ることになる。インセンティブ比率が下がるため、額面の設計をどう組むかが交渉の中心になる。',
    before: { industry: 'M&A', companies: ['M&A仲介会社（上場）', 'M&Aブティック', '独立系FA', '証券会社のIB部門'], roles: ['M&Aアドバイザー', 'FA（ファイナンシャルアドバイザー）', 'M&Aコンサルタント'] },
    after: { industry: '事業会社', companies: ['東証プライム上場企業', '大手事業会社', '成長企業（上場準備中）', '上場SaaS企業'], roles: ['経営企画（M&A担当）', 'M&A・アライアンス担当', '事業開発マネージャー'] },
    age: [28, 42], income: [800, 1800], delta: [-500, 50],
    motives: ['work', 'domain', 'people'], barriers: ['overqual', 'industrygap', 'nomanage'], breaks: ['negotiate', 'narrow', 'reframe'],
    incomeLogic: ['flat_tradeoff', 'down_then_up', 'up_role'], takeaways: ['tradeoff', 'income'],
    tags: ['事業会社のM&A', '年収', 'ポストM&A'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。成約数も報酬も伸びていたが、譲渡が完了した後の会社がどうなったかを知る機会はほとんどなかった。`,
      (c) => `${c.years}年で複数のディールを担当。${c.age}歳になり、案件を回し続ける働き方を続けるかどうかを考えるタイミングが来ていた。`,
    ],
  }),
  P({
    slug: 'shoken-to-ib-fa', area: 'ma',
    label: '証券会社のリテール → IB・FA部門',
    question: '証券のリテール営業からIBやFAに移るのは現実的ですか。',
    lead: '社内異動が最短だが、枠が限られるため外に出る選択になることが多い。財務の基礎とモデリングを自分で埋めてから応募したかどうかが、はっきり結果に出る。',
    before: { industry: '証券', companies: ['大手証券会社', '準大手証券会社', 'ネット証券'], roles: ['リテール営業', '法人営業', 'ウェルスマネジメント'] },
    after: { industry: 'M&A・投資銀行', companies: ['独立系FA', 'M&Aブティック', '証券会社のIB部門', '外資系金融機関'], roles: ['FA（ファイナンシャルアドバイザー）', 'IBアナリスト', 'M&Aアドバイザー'] },
    age: [25, 33], income: [500, 900], delta: [50, 400],
    motives: ['skill', 'income', 'upstream'], barriers: ['industrygap', 'nonum', 'english'], breaks: ['study', 'casestudy', 'narrow'],
    incomeLogic: ['up_scope', 'up_scarcity', 'up_stage'], takeaways: ['evidence', 'income'],
    tags: ['投資銀行', '金融出身', 'モデリング'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}を${c.years}年。数字は作れていたが、扱う商品は決まっており、企業の資本政策そのものに関わる仕事に移りたいと考えていた。`,
      (c) => `${c.years}年目の${c.beforeRole}。社内公募のIB部門に応募したが枠が埋まっており、外部での機会を探すことにした。`,
    ],
  }),
  P({
    slug: 'jigyou-to-pmi', area: 'ma',
    label: '事業会社の実務 → PMI支援・買収後の統合',
    question: '事業会社の現場経験はPMIの仕事で評価されますか。',
    lead: '買収後の統合は、理論より現場を動かした経験が効く領域。ディールの経験がないことは、必ずしも不利にならない。',
    before: { industry: '事業会社', companies: ['東証プライム上場のメーカー', '大手サービス業', '大手小売企業', '上場企業の事業会社'], roles: ['経営企画', '業務改革担当', '人事企画', '情報システム部門'] },
    after: { industry: 'M&A・FAS', companies: ['FAS（大手系）', 'コンサルティングファームのPMI部門', '独立系FAS'], roles: ['PMIコンサルタント', '統合支援コンサルタント', 'シニアコンサルタント'] },
    age: [28, 42], income: [550, 900], delta: [50, 300],
    motives: ['skill', 'income', 'scope'], barriers: ['industrygap', 'nonum', 'agefit'], breaks: ['domainbridge', 'number', 'study'],
    incomeLogic: ['up_domain', 'up_scarcity', 'up_scope'], takeaways: ['bridge', 'income'],
    tags: ['PMI', '未経験からコンサル', '事業会社出身'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。グループ会社の統合プロジェクトに現場側の責任者として関わり、制度と業務を揃える難しさを経験した。`,
      (c) => `${c.years}年在籍した${c.beforeCompany}で、買収した子会社の業務統合を担当。外部のコンサルタントと働く中で、支援する側の仕事に関心を持った。`,
    ],
  }),

  /* ================= PM・PdM・PMO ================= */
  P({
    slug: 'sier-pjm-to-saas-pdm', area: 'pm',
    label: '大手SIerのPjM → SaaS企業のPdM',
    question: 'SIerでPMをしています。年収を下げずにSaaS企業のPdMへ転職できますか。',
    lead: 'このサイトで最も相談が多い移動。「作る責任」から「何を作るか決める責任」への移行で、管理の実績がそのままでは評価されない。前職の規模が大きいほど、当事者性の説明が難しくなる。',
    before: { industry: 'SIer・システムインテグレーション', companies: ['大手SIer（メーカー系）', '大手SIer（ユーザー系）', '大手SIer（独立系）', '大手通信系SIer'], roles: ['プロジェクトマネージャー', 'PjM', 'プロジェクトリーダー'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', 'シリーズBのSaaSスタートアップ', '大手企業の新規プロダクト部門'], roles: ['プロダクトマネージャー', 'PdM', 'シニアプロダクトマネージャー'] },
    age: [28, 40], income: [600, 1000], delta: [-80, 250],
    motives: ['product', 'scope', 'income', 'speed'], barriers: ['noselfdev', 'bigco', 'vendorside', 'coordinator'], breaks: ['reframe', 'portfolio', 'narrow', 'number'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_scarcity', 'up_negotiation'], takeaways: ['reframe', 'income', 'bridge'],
    tags: ['PdM', 'SIer出身', 'SaaS', '年収維持'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。直近は${c.teamSize}名規模の開発体制を率い、大手顧客の基幹システム刷新を担当していた。予算と納期の責任は負っていたが、何を作るかは顧客が決めていた。`,
      (c) => `新卒で${c.beforeCompany}に入り、${c.years}年目に${c.beforeRole}へ。複数のベンダーが入る案件の全体を見る立場で、社内では順調なキャリアだった。一方で、リリース後の利用状況を追う習慣は組織になかった。`,
    ],
  }),
  P({
    slug: 'sier-pjm-to-jigyou-pm', area: 'pm',
    label: '大手SIerのPjM → 事業会社の社内PM・DX推進',
    question: 'SIerのPMから事業会社の社内PMに移るとどうなりますか。',
    lead: 'ベンダーから発注側へ。仕事の進め方は近いが、評価されるのは「社内をどう動かしたか」に変わる。予算取りと部門調整の経験がないことが最初の壁になりやすい。',
    before: { industry: 'SIer・システムインテグレーション', companies: ['大手SIer（メーカー系）', '大手SIer（独立系）', '大手通信系SIer', '中堅SIer'], roles: ['プロジェクトマネージャー', 'PjM', 'ITアーキテクト'] },
    after: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '大手小売企業', '大手サービス業'], roles: ['社内PM', 'DX推進担当', 'IT企画マネージャー', '情報システム部門のPM'] },
    age: [29, 45], income: [600, 1000], delta: [-50, 200],
    motives: ['work', 'upstream', 'scope'], barriers: ['vendorside', 'bigco', 'agefit'], breaks: ['reframe', 'domainbridge', 'number'],
    incomeLogic: ['flat_tradeoff', 'up_scope', 'up_role'], takeaways: ['tradeoff', 'reframe'],
    tags: ['社内PM', 'DX推進', 'SIer出身'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}を${c.years}年。常駐先が変わるたびに業界の知識をゼロから積み直す進み方に、疲れが出ていた。同じ会社の中で知識を積み上げたいと考えるようになった。`,
      (c) => `${c.years}年間、${c.beforeCompany}の${c.beforeRole}として複数業界の案件を担当。${c.age}歳を機に、勤務地と稼働を安定させたいという事情もあり、事業会社側を検討し始めた。`,
    ],
  }),
  P({
    slug: 'web-director-to-pdm', area: 'pm',
    label: 'Webディレクター → プロダクトマネージャー',
    question: 'WebディレクターからPdMになれますか。何を追加で身につける必要がありますか。',
    lead: '進行管理の経験は前提として扱われ、評価は「数字で意思決定した経験」に集中する。指標の設計に関わったことがあるかどうかで、通過率が大きく変わる。',
    before: { industry: 'Web・広告', companies: ['Web制作会社', '広告代理店', '事業会社のWeb部門', 'デジタルエージェンシー'], roles: ['Webディレクター', 'プロジェクトディレクター', 'サービス企画'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['シリーズBのSaaSスタートアップ', '上場SaaS企業', 'BtoCサービス企業', 'シリーズAのスタートアップ'], roles: ['プロダクトマネージャー', 'PdM', 'アソシエイトPdM'] },
    age: [26, 36], income: [400, 700], delta: [50, 300],
    motives: ['product', 'income', 'skill'], barriers: ['nonum', 'nohandson', 'noselfdev'], breaks: ['number', 'portfolio', 'study'],
    incomeLogic: ['up_scope', 'up_scarcity', 'up_role'], takeaways: ['evidence', 'income'],
    tags: ['PdM', 'Web出身', '未経験からPdM'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。案件を回す力はついたが、公開した後の数字を見て次を決める経験がなかった。作って終わる進め方から抜けたかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。自社サービスの改善に関わる機会があり、仮説を立てて検証する仕事の面白さを知った。`,
    ],
  }),
  P({
    slug: 'engineer-to-pm', area: 'pm',
    label: 'エンジニア → PM・PdM',
    question: 'エンジニアからPMに移ると年収は下がりますか。技術を捨てることになりますか。',
    lead: '技術的な判断ができるPMは希少で、評価は高い。一方で、実装から離れることへの本人の納得と、コードを書かない立場での貢献の説明が論点になる。',
    before: { industry: 'IT・ソフトウェア', companies: ['上場SaaS企業', '大手Web企業', '受託開発企業', 'シリーズBのSaaSスタートアップ'], roles: ['バックエンドエンジニア', 'フルスタックエンジニア', 'テックリード', 'フロントエンドエンジニア'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ'], roles: ['プロダクトマネージャー', 'PdM', 'テクニカルPdM'] },
    age: [27, 40], income: [550, 950], delta: [-50, 250],
    motives: ['scope', 'product', 'people'], barriers: ['nomanage', 'nonum', 'coordinator'], breaks: ['reframe', 'number', 'firstline'],
    incomeLogic: ['up_scope', 'up_scarcity', 'flat_tradeoff'], takeaways: ['reframe', 'tradeoff'],
    tags: ['PdM', 'エンジニア出身', 'キャリアチェンジ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。実装の質には自信があったが、作る前の意思決定に関われないもどかしさがあった。仕様が決まってから渡される構造を変えたかった。`,
      (c) => `${c.years}年エンジニアとして働き、直近は${c.teamSize}名のチームの技術的な意思決定を担当。人と要件の調整に時間を使う割合が増え、役割の変更を考えるようになった。`,
    ],
  }),
  P({
    slug: 'consul-to-pdm', area: 'pm',
    label: 'コンサルタント → PdM',
    question: 'コンサルからPdMに移れますか。事業会社側では何が足りないと見られますか。',
    lead: '仮説を立てて検証する型は評価される。足りないと見られるのは、開発チームと同じ時間軸で意思決定した経験と、技術的な制約の理解。',
    before: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', '戦略系コンサルティングファーム', 'IT系コンサルティングファーム'], roles: ['コンサルタント', 'シニアコンサルタント', 'マネージャー'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', 'シリーズBのSaaSスタートアップ', '大手Web企業'], roles: ['プロダクトマネージャー', 'PdM', 'シニアプロダクトマネージャー'] },
    age: [27, 38], income: [700, 1200], delta: [-200, 150],
    motives: ['product', 'work', 'domain'], barriers: ['nohandson', 'overqual', 'noselfdev'], breaks: ['portfolio', 'study', 'negotiate'],
    incomeLogic: ['flat_tradeoff', 'down_then_up', 'up_scope'], takeaways: ['tradeoff', 'evidence'],
    tags: ['PdM', 'ポストコンサル', 'SaaS'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。提言までは行うが実装は顧客側という分担に、物足りなさがあった。自分が決めたものが動くところまで見たかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。プロダクト開発の支援案件をきっかけに、支援ではなく事業側に立つ選択を考え始めた。`,
    ],
  }),
  P({
    slug: 'pmo-to-jigyou-pm', area: 'pm',
    label: 'PMO → 事業会社のPM',
    question: 'PMOからPMになれますか。管理と推進の違いはどう説明すればいいですか。',
    lead: '「回した」ではなく「決めた」が言えるかどうか。PMOの経験は幅広い一方で、責任の所在が曖昧に見えやすい点を自分で補う必要がある。',
    before: { industry: 'コンサルティング・SIer', companies: ['総合系コンサルティングファーム', '大手SIer（独立系）', 'IT系コンサルティングファーム', '大手SIer（メーカー系）'], roles: ['PMO', 'PMOコンサルタント', 'プロジェクト管理'] },
    after: { industry: '事業会社', companies: ['東証プライム上場企業', '上場SaaS企業', '大手サービス業', '成長企業（上場準備中）'], roles: ['社内PM', 'プロジェクトマネージャー', 'PMOマネージャー', 'DX推進マネージャー'] },
    age: [28, 42], income: [550, 950], delta: [-30, 200],
    motives: ['scope', 'work', 'domain'], barriers: ['coordinator', 'nonum', 'bigco'], breaks: ['reframe', 'number', 'firstline'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_role'], takeaways: ['reframe', 'evidence'],
    tags: ['PMO', '社内PM', '職務経歴書'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。複数のプロジェクトを横断して見る立場で、経営会議への報告も担当していた。ただ、意思決定の当事者ではなかった。`,
      (c) => `${c.years}年間PMOに従事。案件が変わるたびに関係者との関係を作り直す進め方が続き、一つの組織に腰を据えたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'pdm-to-senior-pdm', area: 'pm',
    label: 'PdM → シニアPdM・プロダクト責任者',
    question: 'PdMとして次のステップに進むには、どんな経験が必要ですか。',
    lead: '単一機能の担当から、プロダクト全体や複数チームの責任へ。何を作ったかより、何を作らないと決めたかを説明できるかで評価が分かれる。',
    before: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', '大手Web企業', 'シリーズCのSaaS企業'], roles: ['プロダクトマネージャー', 'PdM', 'アソシエイトPdM'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズDのSaaS企業', '大手Web企業', 'シリーズCのSaaS企業'], roles: ['シニアプロダクトマネージャー', 'プロダクト責任者', 'グループPdM', 'VPoP候補'] },
    age: [29, 42], income: [700, 1200], delta: [50, 350],
    motives: ['scope', 'people', 'income'], barriers: ['nomanage', 'nonum', 'agefit'], breaks: ['number', 'reframe', 'negotiate'],
    incomeLogic: ['up_role', 'up_scope', 'up_negotiation'], takeaways: ['income', 'reframe'],
    tags: ['PdM', 'マネジメント', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。担当プロダクトの数字は伸ばしてきたが、担当範囲が固定されており、次の役割が社内に用意されていなかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。${c.teamSize}名の開発チームと組んで機能開発を進めてきたが、プロダクト全体の方針は上位者が決めていた。`,
    ],
  }),
  P({
    slug: 'sales-cs-to-pdm', area: 'pm',
    label: '営業・カスタマーサクセス → PdM',
    question: '営業やCSからPdMになれますか。開発経験がないことは致命的ですか。',
    lead: '顧客の声を最も持っている職種からの移動。技術の理解を後から埋められるかが論点で、社内異動を経てから外に出るケースが多い。',
    before: { industry: 'SaaS・IT', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', '大手IT企業', '中堅SaaS企業'], roles: ['カスタマーサクセス', 'フィールドセールス', 'ソリューション営業', 'CSマネージャー'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['シリーズBのSaaSスタートアップ', '上場SaaS企業', 'シリーズAのスタートアップ', '中堅SaaS企業'], roles: ['プロダクトマネージャー', 'PdM', 'アソシエイトPdM'] },
    age: [26, 36], income: [450, 750], delta: [0, 250],
    motives: ['product', 'skill', 'scope'], barriers: ['nohandson', 'noselfdev', 'nonum'], breaks: ['portfolio', 'study', 'number'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_domain'], takeaways: ['bridge', 'evidence'],
    tags: ['PdM', 'CS出身', '未経験からPdM'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。解約の理由を最も聞いている立場だったが、その情報がプロダクトに反映されるまでには時間がかかった。自分で反映する側に回りたいと考えた。`,
      (c) => `${c.years}年間、顧客に最も近い場所で働いてきた。要望を開発に伝える役割は担っていたが、優先順位を決めるのは別の人だった。`,
    ],
  }),
  P({
    slug: 'sier-pjm-to-startup-pm', area: 'pm',
    label: '大手SIerのPjM → シード〜シリーズAのスタートアップ',
    question: '大手SIerから初期フェーズのスタートアップに移るのはどうですか。年収は下がりますか。',
    lead: '最も落差が大きい移動。整った環境での実績がほぼ評価されず、無い状態を作れるかだけが問われる。年収は下がることが多いが、株式報酬を含めた設計次第で見え方が変わる。',
    before: { industry: 'SIer・システムインテグレーション', companies: ['大手SIer（メーカー系）', '大手SIer（ユーザー系）', '大手通信系SIer', '大手SIer（独立系）'], roles: ['プロジェクトマネージャー', 'PjM', 'プロジェクトリーダー'] },
    after: { industry: 'スタートアップ', companies: ['シードのスタートアップ', 'シリーズAのスタートアップ', 'シリーズAのSaaSスタートアップ'], roles: ['PM', 'プロダクトマネージャー', '事業責任者', '開発責任者'] },
    age: [27, 40], income: [600, 950], delta: [-250, 100],
    motives: ['scope', 'speed', 'product'], barriers: ['bigco', 'noselfdev', 'overqual'], breaks: ['scale', 'trial', 'negotiate'],
    incomeLogic: ['down_then_up', 'up_stage', 'flat_tradeoff'], takeaways: ['tradeoff', 'income'],
    tags: ['スタートアップ', 'SIer出身', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}を${c.years}年。安定した環境と手厚い制度がある一方で、自分がいなくても回る仕事をしている感覚が拭えなかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。${c.age}歳という年齢を考えて、リスクを取れる最後のタイミングかもしれないと考えた。`,
    ],
  }),

  /* ================= エンジニア・IT ================= */
  P({
    slug: 'sier-se-to-jigyou-engineer', area: 'eng',
    label: 'SIerのSE → 事業会社の自社開発エンジニア',
    question: 'SIerから自社開発の会社に移れますか。実装経験が浅いと難しいですか。',
    lead: '最も相談の多い移動。設計書を書く仕事と、動くものを作り続ける仕事の差が論点になる。直近で自分が書いたコードを示せるかどうかで結果が変わる。',
    before: { industry: 'SIer・システムインテグレーション', companies: ['大手SIer（メーカー系）', '大手SIer（独立系）', '中堅SIer', '大手通信系SIer'], roles: ['システムエンジニア', 'アプリケーションエンジニア', '業務システムのSE'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ', '事業会社の内製開発組織'], roles: ['バックエンドエンジニア', 'ソフトウェアエンジニア', 'サーバーサイドエンジニア'] },
    age: [24, 35], income: [400, 750], delta: [0, 250],
    motives: ['product', 'skill', 'income'], barriers: ['nohandson', 'noselfdev', 'nonum'], breaks: ['portfolio', 'study', 'narrow'],
    incomeLogic: ['up_scope', 'up_scarcity', 'flat_tradeoff'], takeaways: ['evidence', 'income'],
    tags: ['自社開発', 'SIer出身', 'ポートフォリオ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。設計とテストが中心で、実装はパートナー企業が担当する体制だった。技術の話はできるが、書いたコードの量は年々減っていた。`,
      (c) => `${c.years}年目の${c.beforeRole}。担当した案件の技術選定は顧客の標準に従うもので、自分で選んだ経験がなかった。`,
    ],
  }),
  P({
    slug: 'ses-to-jigyou-engineer', area: 'eng',
    label: 'SES → 事業会社の自社開発エンジニア',
    question: 'SESから自社開発に転職できますか。経歴が細切れなのが不安です。',
    lead: '常駐先が変わり続けることで、経験が分散して見えやすい。技術スタックを軸に一貫性を再構成できるかが最初の作業になる。',
    before: { industry: 'SES・受託開発', companies: ['SES企業', '中堅の受託開発企業', '独立系の技術者派遣企業'], roles: ['システムエンジニア', 'プログラマー', 'インフラエンジニア'] },
    after: { industry: 'IT・自社サービス', companies: ['シリーズBのSaaSスタートアップ', '上場SaaS企業', '事業会社の内製開発組織', '中堅Web企業'], roles: ['バックエンドエンジニア', 'ソフトウェアエンジニア', 'フルスタックエンジニア'] },
    age: [24, 34], income: [350, 600], delta: [30, 250],
    motives: ['work', 'income', 'product'], barriers: ['shortterm', 'nohandson', 'nonum'], breaks: ['portfolio', 'reframe', 'study'],
    incomeLogic: ['up_scope', 'up_scarcity', 'up_role'], takeaways: ['evidence', 'reframe'],
    tags: ['SES', '自社開発', 'ポートフォリオ'],
    situations: [
      (c) => `${c.beforeCompany}に所属し、${c.years}年で複数の常駐先を経験。技術の幅は広がったが、一つのプロダクトに長く関わったことがなかった。`,
      (c) => `${c.years}年間、常駐先で開発に従事。案件ごとに使う技術が変わり、どれも中途半端に見えることが職務経歴書を書くときの悩みだった。`,
    ],
  }),
  P({
    slug: 'embedded-to-iot-product', area: 'eng',
    label: '組込みエンジニア → IoT・プロダクト開発',
    question: '組込みエンジニアの年収を上げるには、どこへ移るのが現実的ですか。',
    lead: '技術の難易度に対して報酬が低く抑えられやすい領域。同じ技術のまま、事業構造が違う会社に移ることで水準が変わることが多い。',
    before: { industry: 'メーカー・組込み', companies: ['大手電機メーカー', '大手部品メーカー', '中堅の組込み受託企業', '大手自動車部品メーカー'], roles: ['組込みソフトウェアエンジニア', 'ファームウェアエンジニア', '制御ソフト開発'] },
    after: { industry: 'IoT・ハードウェアプロダクト', companies: ['IoTプロダクト企業', 'シリーズBのハードウェアスタートアップ', '上場企業の新規プロダクト部門', '外資系メーカーの日本法人'], roles: ['組込みエンジニア', 'IoTエンジニア', 'プロダクト開発エンジニア', 'テックリード'] },
    age: [27, 45], income: [450, 800], delta: [50, 300],
    motives: ['income', 'product', 'skill'], barriers: ['nonum', 'bigco', 'agefit'], breaks: ['number', 'reframe', 'narrow'],
    incomeLogic: ['up_stage', 'up_scarcity', 'up_scope'], takeaways: ['income', 'reframe'],
    tags: ['組込み', 'IoT', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。制御の難易度は高く、社内では中核の技術者だった。ただ、部品事業の利益構造の中では報酬の上限が決まっていた。`,
      (c) => `${c.years}年間、${c.beforeRole}として量産製品の開発に従事。技術力には自信があったが、同年代の Web 系エンジニアとの年収差を知って考え始めた。`,
    ],
  }),
  P({
    slug: 'infra-to-sre', area: 'eng',
    label: 'インフラ運用 → SRE',
    question: 'インフラ運用からSREになれますか。コードが書けないと厳しいですか。',
    lead: '運用を自動化した経験があるかどうかが、ほぼ唯一の判断材料になる。手順書に沿って運用してきただけの経歴では通らない。',
    before: { industry: 'SIer・IT運用', companies: ['大手SIer（独立系）', 'データセンター事業者', '大手通信系SIer', 'SES企業'], roles: ['インフラエンジニア', '運用保守エンジニア', 'ネットワークエンジニア'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズCのSaaS企業', '事業会社の内製開発組織'], roles: ['SRE', 'プラットフォームエンジニア', 'インフラエンジニア（クラウド）'] },
    age: [25, 40], income: [400, 750], delta: [50, 300],
    motives: ['skill', 'income', 'product'], barriers: ['nohandson', 'nonum', 'noselfdev'], breaks: ['portfolio', 'study', 'number'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_role'], takeaways: ['evidence', 'income'],
    tags: ['SRE', 'インフラ', 'クラウド'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。オンプレミス環境の運用が中心で、手順書に沿った作業が業務の大半を占めていた。`,
      (c) => `${c.years}年間、24時間体制の運用に従事。自動化の必要性は感じていたが、変更を提案できる立場ではなかった。`,
    ],
  }),
  P({
    slug: 'engineer-to-fde', area: 'eng',
    label: 'SIer・受託のエンジニア → FDE（フォワードデプロイドエンジニア）',
    question: 'FDEとはどんな職種ですか。SIerの経験は活きますか。',
    lead: '顧客先に入り込んで、実装しながら要件を決める職種。SIerや受託で「調整」と呼ばれてきた仕事が、そのまま中核業務として評価される数少ない移動。',
    before: { industry: 'SIer・受託開発', companies: ['大手SIer（独立系）', '中堅の受託開発企業', '大手SIer（メーカー系）', 'SES企業'], roles: ['システムエンジニア', 'プロジェクトリーダー', 'ソリューションエンジニア'] },
    after: { industry: 'SaaS・スタートアップ', companies: ['シリーズBのSaaSスタートアップ', '外資系ソフトウェア企業の日本法人', '上場SaaS企業', 'シリーズCのSaaS企業'], roles: ['フォワードデプロイドエンジニア', 'ソリューションアーキテクト', '導入エンジニア'] },
    age: [26, 42], income: [500, 900], delta: [50, 350],
    motives: ['scope', 'product', 'income'], barriers: ['coordinator', 'nonum', 'english'], breaks: ['reframe', 'domainbridge', 'number'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_stage'], takeaways: ['reframe', 'bridge'],
    tags: ['FDE', 'SIer出身', 'ソリューションアーキテクト'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。顧客の業務を理解して仕様に落とす仕事を続けてきたが、社内では「技術力より調整力の人」と見られていた。`,
      (c) => `${c.years}年目の${c.beforeRole}。顧客先に常駐して要件を固めながら実装する働き方が長く、それが自分の型になっていた。`,
    ],
  }),
  P({
    slug: 'engineer-to-em', area: 'eng',
    label: 'エンジニア → エンジニアリングマネージャー',
    question: 'EMになるとキャリアはどうなりますか。技術から離れることに不安があります。',
    lead: '技術的な判断とピープルマネジメントの両方を求められる役割。プレイヤーとしての実績だけでは評価されず、人を伸ばした具体例が必要になる。',
    before: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ', '受託開発企業'], roles: ['テックリード', 'バックエンドエンジニア', 'シニアエンジニア'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', '大手Web企業', '事業会社の内製開発組織'], roles: ['エンジニアリングマネージャー', '開発マネージャー', 'VPoE候補'] },
    age: [28, 44], income: [600, 1000], delta: [50, 300],
    motives: ['people', 'scope', 'income'], barriers: ['nomanage', 'nonum', 'nohandson'], breaks: ['number', 'reframe', 'reference'],
    incomeLogic: ['up_role', 'up_scope', 'up_negotiation'], takeaways: ['reframe', 'income'],
    tags: ['EM', 'マネジメント', 'エンジニア'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。${c.teamSize}名のチームで技術的な意思決定を担ってきたが、評価や採用には関わっていなかった。`,
      (c) => `${c.years}年目。実装の速さでは若手に及ばない場面が出てきて、価値の出し方を変える時期だと考えるようになった。`,
    ],
  }),
  P({
    slug: 'unexperienced-to-engineer', area: 'eng',
    label: '未経験（別職種） → エンジニア',
    question: '未経験からエンジニアになれますか。年齢的に厳しいでしょうか。',
    lead: '入社できるかと、3年後に困らないかは別の問題。教育体制と、最初に触る技術の選択で、その後のキャリアの幅が決まる。',
    before: { industry: '他業界', companies: ['大手小売企業', '人材サービス企業', '大手メーカーの事務職', '金融機関'], roles: ['営業', '販売', '事務', 'カスタマーサポート'] },
    after: { industry: 'IT・ソフトウェア', companies: ['自社サービスを持つIT企業', '中堅の受託開発企業', '事業会社の内製開発組織', 'シリーズAのスタートアップ'], roles: ['エンジニア（ジュニア）', 'バックエンドエンジニア', 'テストエンジニア'] },
    age: [22, 32], income: [280, 480], delta: [-80, 120],
    motives: ['skill', 'work', 'income'], barriers: ['nohandson', 'agefit', 'industrygap'], breaks: ['portfolio', 'study', 'narrow'],
    incomeLogic: ['down_then_up', 'flat_tradeoff', 'up_scope'], takeaways: ['timing', 'evidence'],
    tags: ['未経験からエンジニア', 'ポートフォリオ', 'キャリアチェンジ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。仕事は回せていたが、この先も同じ業務を続けることに将来性を感じられなかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。社内システムの改善を独学で手伝ったことがきっかけで、作る側への関心が強くなった。`,
    ],
  }),
  P({
    slug: 'onpre-to-cloud', area: 'eng',
    label: 'オンプレミス中心 → クラウドエンジニア',
    question: 'オンプレの経験しかなくてもクラウドの求人に応募できますか。',
    lead: '技術の置き換えではなく、設計思想の切り替えが問われる。資格だけでは通らず、実際に構築した環境を示せるかが分かれ目になる。',
    before: { industry: 'SIer・IT運用', companies: ['大手SIer（独立系）', '大手SIer（メーカー系）', 'データセンター事業者', '中堅SIer'], roles: ['インフラエンジニア', 'サーバーエンジニア', 'ネットワークエンジニア'] },
    after: { industry: 'IT・クラウド', companies: ['クラウドインテグレーター', '上場SaaS企業', '事業会社の内製開発組織', '外資系クラウドベンダーのパートナー企業'], roles: ['クラウドエンジニア', 'インフラエンジニア（クラウド）', 'ソリューションアーキテクト'] },
    age: [25, 42], income: [400, 800], delta: [50, 280],
    motives: ['skill', 'income', 'work'], barriers: ['nohandson', 'industrygap', 'nonum'], breaks: ['study', 'portfolio', 'number'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_role'], takeaways: ['evidence', 'income'],
    tags: ['クラウド', 'インフラ', '資格'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。オンプレミスの設計と構築が中心で、クラウドは検証環境で触った程度だった。`,
      (c) => `${c.years}年間、物理環境の運用設計を担当。案件がクラウド前提に変わり始め、このままでは仕事がなくなると感じた。`,
    ],
  }),
  P({
    slug: 'qa-to-sdet', area: 'eng',
    label: 'QA・テスト → SDET・品質エンジニアリング',
    question: 'テスト業務からエンジニア寄りのキャリアに移れますか。',
    lead: '手動テストの経験だけでは評価が伸びない。テストを自動化した経験、あるいは品質の基準を設計した経験があるかが問われる。',
    before: { industry: 'SIer・受託開発', companies: ['大手SIer（独立系）', 'テスト専門企業', '中堅の受託開発企業', 'SES企業'], roles: ['テストエンジニア', 'QAエンジニア', '品質保証担当'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ', '事業会社の内製開発組織'], roles: ['SDET', 'QAエンジニア', '品質エンジニアリング担当'] },
    age: [25, 40], income: [380, 700], delta: [50, 250],
    motives: ['skill', 'income', 'product'], barriers: ['nohandson', 'nonum', 'noselfdev'], breaks: ['portfolio', 'number', 'study'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_role'], takeaways: ['evidence', 'income'],
    tags: ['QA', 'テスト自動化', 'SDET'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。テスト設計と実行が中心で、開発チームとは別の組織に所属していた。`,
      (c) => `${c.years}年間、品質保証に従事。自動化の必要性は感じていたが、工数として認められていなかった。`,
    ],
  }),
  P({
    slug: 'engineer-to-presales', area: 'eng',
    label: 'エンジニア → プリセールス・ソリューションアーキテクト',
    question: 'エンジニアからプリセールスに移るとキャリアはどうなりますか。',
    lead: '技術と商談の両方に立つ役割。技術力の証明に加えて、顧客の前で判断した経験があるかどうかが評価の中心になる。',
    before: { industry: 'IT・SIer', companies: ['大手SIer（メーカー系）', '上場SaaS企業', '中堅の受託開発企業', '大手通信系SIer'], roles: ['システムエンジニア', 'バックエンドエンジニア', 'インフラエンジニア', 'テックリード'] },
    after: { industry: 'SaaS・外資系IT', companies: ['外資系ソフトウェア企業の日本法人', '上場SaaS企業', 'シリーズCのSaaS企業', 'クラウドインテグレーター'], roles: ['プリセールスエンジニア', 'ソリューションアーキテクト', 'セールスエンジニア'] },
    age: [27, 44], income: [500, 900], delta: [50, 350],
    motives: ['income', 'scope', 'skill'], barriers: ['english', 'nonum', 'coordinator'], breaks: ['reframe', 'number', 'narrow'],
    incomeLogic: ['up_stage', 'up_scarcity', 'up_role'], takeaways: ['income', 'reframe'],
    tags: ['プリセールス', 'ソリューションアーキテクト', '外資系'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。提案の技術検討には関わっていたが、商談の場に出ることは少なかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。顧客への説明を任される機会が増え、その仕事のほうが向いているのではないかと考えるようになった。`,
    ],
  }),

  /* ================= 事業開発・経営企画 ================= */
  P({
    slug: 'consul-to-startup-bizdev', area: 'biz',
    label: 'コンサルタント → スタートアップの事業開発',
    question: 'コンサルからスタートアップの事業開発に移るとどうなりますか。',
    lead: '提案する側から、実行して数字を持つ側へ。分析力は前提として扱われ、リソースがない中で自分で動いた経験があるかが問われる。',
    before: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', '戦略系コンサルティングファーム', '外資系コンサルティングファーム（総合）'], roles: ['コンサルタント', 'シニアコンサルタント', 'マネージャー'] },
    after: { industry: 'スタートアップ', companies: ['シリーズBのスタートアップ', 'シリーズCのSaaS企業', 'シリーズAのスタートアップ', '上場準備中のスタートアップ'], roles: ['事業開発', 'BizDev', '事業責任者', '経営企画'] },
    age: [26, 38], income: [700, 1200], delta: [-300, 100],
    motives: ['product', 'scope', 'speed'], barriers: ['overqual', 'nohandson', 'nonum'], breaks: ['narrow', 'negotiate', 'trial'],
    incomeLogic: ['flat_tradeoff', 'down_then_up', 'up_stage'], takeaways: ['tradeoff', 'income'],
    tags: ['スタートアップ', 'ポストコンサル', '事業開発'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。戦略の提言は行うが、実行してどうなったかを見届ける機会は少なかった。数字を持つ側に回りたかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。支援先のスタートアップの動きの速さに触れ、自分もその側で働きたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'sales-to-saas-cs', area: 'biz',
    label: '営業 → SaaSのカスタマーサクセス',
    question: '営業からSaaSのCSに移るとどう変わりますか。年収は下がりますか。',
    lead: '売る仕事から、使い続けてもらう仕事へ。短期の成果ではなく、継続率という中期の指標で評価される点への切り替えが論点になる。',
    before: { industry: '営業', companies: ['人材サービス企業', '広告代理店', '大手メーカー', '中堅IT企業'], roles: ['法人営業', 'フィールドセールス', 'ソリューション営業'] },
    after: { industry: 'SaaS', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', 'シリーズCのSaaS企業', '中堅SaaS企業'], roles: ['カスタマーサクセス', 'CSマネージャー', 'オンボーディング担当'] },
    age: [24, 36], income: [400, 700], delta: [-50, 200],
    motives: ['skill', 'work', 'product'], barriers: ['industrygap', 'nonum', 'nohandson'], breaks: ['study', 'number', 'domainbridge'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_domain'], takeaways: ['bridge', 'income'],
    tags: ['カスタマーサクセス', 'SaaS', '営業出身'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。新規の獲得は得意だったが、売った後に関われない構造に物足りなさがあった。`,
      (c) => `${c.years}年間、${c.beforeRole}として数字を追ってきた。単月の達成を繰り返す働き方から、積み上げ型の指標を扱う仕事へ移りたいと考えた。`,
    ],
  }),
  P({
    slug: 'jigyou-to-keiei-kikaku', area: 'biz',
    label: '事業部門 → 経営企画',
    question: '現場から経営企画に異動・転職するには何が必要ですか。',
    lead: '現場を知っていることが最大の武器になる一方で、全社の数字を扱った経験がないことが必ず論点になる。財務三表を自分で組めるかが一つの基準。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '大手サービス業', '大手小売企業'], roles: ['営業', '事業部門の企画', 'マーケティング', '商品企画'] },
    after: { industry: '事業会社', companies: ['東証プライム上場企業', '成長企業（上場準備中）', '上場SaaS企業', '大手事業会社'], roles: ['経営企画', '事業企画', '経営管理'] },
    age: [26, 42], income: [450, 850], delta: [0, 200],
    motives: ['upstream', 'skill', 'scope'], barriers: ['nonum', 'industrygap', 'bigco'], breaks: ['number', 'study', 'reframe'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_role'], takeaways: ['reframe', 'evidence'],
    tags: ['経営企画', '事業会社', 'キャリアチェンジ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。担当事業の数字は作れていたが、全社の投資判断がどう行われているかは見えていなかった。`,
      (c) => `${c.years}年目。現場の改善提案が上に通らない経験が続き、決める側の仕組みを知りたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'startup-to-later-stage', area: 'biz',
    label: 'アーリーのスタートアップ → レイターステージ・上場企業',
    question: '初期のスタートアップから、もう少し規模の大きい会社に移るのはどうですか。',
    lead: '何でもやってきた経験が、大きな組織では「専門性がない」と見られることがある。どの職種として応募するかを先に決める必要がある。',
    before: { industry: 'スタートアップ', companies: ['シードのスタートアップ', 'シリーズAのスタートアップ', 'シリーズBのスタートアップ'], roles: ['事業開発', '何でも屋（複数職種の兼務）', 'PM', 'マーケティング'] },
    after: { industry: '事業会社・レイターステージ', companies: ['上場SaaS企業', 'シリーズDのSaaS企業', '東証プライム上場企業', '上場準備中のスタートアップ'], roles: ['事業開発マネージャー', '経営企画', 'PdM', '事業責任者'] },
    age: [26, 40], income: [400, 800], delta: [50, 350],
    motives: ['income', 'skill', 'people'], barriers: ['nonum', 'nomanage', 'shortterm'], breaks: ['number', 'reframe', 'narrow'],
    incomeLogic: ['up_scope', 'up_role', 'up_negotiation'], takeaways: ['reframe', 'income'],
    tags: ['スタートアップ', '事業開発', '年収'],
    situations: [
      (c) => `${c.beforeCompany}に${c.years}年。人が足りない分、営業からプロダクトまで幅広く担当してきた。ただ、職務経歴書にすると何の専門家か分からなくなった。`,
      (c) => `${c.years}年間、少人数の組織で事業の立ち上げに関わった。組織が大きくなる過程を経験できる環境に移りたいと考えた。`,
    ],
  }),
  P({
    slug: 'finance-to-startup-corp', area: 'biz',
    label: '金融・監査法人 → スタートアップの管理部門・CFO候補',
    question: '金融からスタートアップの管理部門に移れますか。IPO経験がないと厳しいですか。',
    lead: '資金調達や上場準備を担う役割。経験者が絶対的に少ないため、隣接する経験からの移動が成立しやすい領域。',
    before: { industry: '金融・監査法人', companies: ['メガバンク', '大手監査法人', '大手証券会社', '大手地方銀行'], roles: ['法人営業', '会計監査', '財務', 'IPO支援'] },
    after: { industry: 'スタートアップ', companies: ['シリーズBのスタートアップ', '上場準備中のスタートアップ', 'シリーズCのSaaS企業', 'シリーズAのスタートアップ'], roles: ['管理部門責任者', '経営管理', 'CFO候補', '財務・経理マネージャー'] },
    age: [27, 42], income: [550, 1000], delta: [-150, 250],
    motives: ['scope', 'skill', 'speed'], barriers: ['industrygap', 'nomanage', 'overqual'], breaks: ['domainbridge', 'narrow', 'negotiate'],
    incomeLogic: ['up_stage', 'flat_tradeoff', 'up_scarcity'], takeaways: ['bridge', 'tradeoff'],
    tags: ['CFO候補', 'スタートアップ', '管理部門'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。決められた枠の中で正確に処理する仕事が中心で、仕組みを作る側に回りたいと考えていた。`,
      (c) => `${c.years}年目。担当先のスタートアップの成長過程を外から見る中で、内側から関わりたいという気持ちが強くなった。`,
    ],
  }),
  P({
    slug: 'jinji-to-hrbp', area: 'biz',
    label: '人事 → HRBP・採用責任者',
    question: '人事のキャリアを広げるには、どんな移動が現実的ですか。',
    lead: 'オペレーション中心の人事から、事業に紐づく人事へ。事業側の数字と人事施策をつなげて説明できるかが評価の中心になる。',
    before: { industry: '事業会社・人材', companies: ['東証プライム上場企業', '人材サービス企業', '大手メーカー', '中堅IT企業'], roles: ['人事（採用）', '人事（労務）', '人事企画', 'キャリアアドバイザー'] },
    after: { industry: '事業会社・スタートアップ', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', '成長企業（上場準備中）', 'シリーズBのスタートアップ'], roles: ['HRBP', '採用責任者', '人事マネージャー', '組織開発担当'] },
    age: [26, 42], income: [400, 750], delta: [30, 250],
    motives: ['scope', 'people', 'income'], barriers: ['nonum', 'nomanage', 'industrygap'], breaks: ['number', 'reframe', 'domainbridge'],
    incomeLogic: ['up_scope', 'up_role', 'up_scarcity'], takeaways: ['reframe', 'income'],
    tags: ['人事', 'HRBP', '採用'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。採用の実務は回せていたが、事業側の計画と人員計画がつながっていない状態に課題を感じていた。`,
      (c) => `${c.years}年間、人事に従事。制度の運用が中心で、事業の意思決定に関わる機会は少なかった。`,
    ],
  }),
  P({
    slug: 'marketing-to-saas-marketing', area: 'biz',
    label: 'マーケティング → SaaS・BtoBマーケティング',
    question: 'BtoCのマーケからBtoB SaaSに移れますか。',
    lead: '購買プロセスの長さと関与者の多さが根本的に違う。獲得の指標だけでなく、商談化と受注までを見た経験があるかが問われる。',
    before: { industry: 'マーケティング', companies: ['広告代理店', '大手小売企業', 'BtoCサービス企業', '大手メーカー'], roles: ['マーケティング', 'デジタルマーケティング', '販促企画', '広告運用'] },
    after: { industry: 'SaaS', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', 'シリーズCのSaaS企業', '中堅SaaS企業'], roles: ['BtoBマーケター', 'マーケティングマネージャー', 'デマンドジェネレーション担当'] },
    age: [25, 40], income: [400, 750], delta: [30, 250],
    motives: ['skill', 'income', 'product'], barriers: ['industrygap', 'nonum', 'noselfdev'], breaks: ['study', 'number', 'domainbridge'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_domain'], takeaways: ['bridge', 'evidence'],
    tags: ['BtoBマーケ', 'SaaS', 'マーケティング'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。獲得単価の改善は得意だったが、その先の売上への貢献までは追えていなかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。担当していた領域が広告運用に寄っており、事業全体のマーケティングに関わりたいと考えた。`,
    ],
  }),
];

/* 追加分は必ず末尾に連結する。順番＝事例の通し番号＝URL なので、
   途中に入れると公開済みURLの中身が入れ替わる。 */
export const AREAS = { ...AREAS_CORE, ...AREAS_EXTRA };
export const PATTERNS = [...PATTERNS_CORE, ...PATTERNS_EXTRA];

export const PATTERN_BY_SLUG = new Map(PATTERNS.map((p) => [p.slug, p]));
