// tools/cases/patterns-extra.mjs … 転職パターンの追加分（40種）。
//
// ⚠ 必ず patterns.mjs の後ろに連結する。事例の通し番号（= seed = URL）は
//   パターンの並び順で決まるので、**先頭や途中に挿し込むと公開済みのURLの中身が入れ替わる。**
//   増やすときは、必ずこの配列の末尾に足すこと。
//
// 実在の企業名は書かない（patterns.mjs と同じ）。

/** 領域の追加。既存5領域は patterns.mjs 側にある */
export const AREAS_EXTRA = {
  data: { label: 'データ・AI', note: '分析職、データ基盤、機械学習・生成AI。隣接職種からの移動が多い領域。' },
  sales: { label: '営業・カスタマーサクセス', note: 'SaaSの営業組織は分業が進んでいて、どの役割で入るかで求められるものが違う。' },
  corp: { label: 'コーポレート・管理部門', note: '経理・法務・人事・広報。事業会社からスタートアップへの移動を中心に。' },
};

const P = (o) => o;

export const PATTERNS_EXTRA = [
  /* ================= コンサルティング（追加6） ================= */
  P({
    slug: 'shosha-to-strategy-consul', area: 'consul',
    label: '総合商社 → 戦略コンサルタント',
    question: '総合商社から戦略コンサルに転職できますか。事業投資の経験は評価されますか。',
    lead: '事業投資と海外での実務を持っている点が強い。一方で、商社の仕事は「関係性と時間」で動く部分が大きく、その部分は選考で評価されにくい。',
    before: { industry: '商社', companies: ['総合商社', '大手専門商社', '総合商社の事業投資部門'], roles: ['事業投資担当', 'トレーディング営業', '事業会社への出向者', '経営企画'] },
    after: { industry: 'コンサルティング', companies: ['戦略系コンサルティングファーム', '外資系コンサルティングファーム（総合）', '大手総合系コンサルティングファーム'], roles: ['コンサルタント', 'シニアコンサルタント', 'アソシエイト'] },
    age: [26, 36], income: [700, 1200], delta: [-100, 300],
    motives: ['skill', 'speed', 'scope'], barriers: ['nonum', 'agefit', 'overqual'], breaks: ['casestudy', 'number', 'reframe'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'up_role'], takeaways: ['reframe', 'income'],
    tags: ['未経験からコンサル', '商社出身', 'ケース面接'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。出資先の管理と新規案件の検討を担当し、海外駐在も経験した。ただ、意思決定の速度と、自分が担う範囲の狭さに物足りなさがあった。`,
      (c) => `${c.years}年目で${c.beforeRole}。扱う金額は大きかったが、案件が動くかどうかは社内の力学で決まる部分が大きかった。`,
    ],
  }),
  P({
    slug: 'jyosys-to-it-consul', area: 'consul',
    label: '事業会社の情報システム部門 → ITコンサルタント',
    question: '情シスからITコンサルに移れますか。ベンダー管理の経験は評価されますか。',
    lead: '発注側の経験を持っている点がベンダー出身者との差になる。予算の作り方と社内の通し方を語れるかが分かれ目。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '大手小売企業', '大手サービス業'], roles: ['情報システム部門', '社内SE', 'IT企画'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', 'IT系コンサルティングファーム', '外資系コンサルティングファーム（総合）'], roles: ['ITコンサルタント', 'シニアコンサルタント', 'テクノロジーコンサルタント'] },
    age: [27, 42], income: [500, 850], delta: [50, 300],
    motives: ['income', 'skill', 'learning'], barriers: ['nonum', 'narrowspec', 'agefit'], breaks: ['domainbridge', 'number', 'casestudy'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_market'], takeaways: ['bridge', 'market'],
    tags: ['情シス', '未経験からコンサル', 'DX推進'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。基幹システムの刷新でベンダーを選定し、社内の要件を取りまとめる立場だった。仕事の中身は上流だが、社内では間接部門の扱いだった。`,
      (c) => `${c.years}年間、${c.beforeRole}。予算取りから稼働後の運用まで一通り見てきたが、社内に同じ仕事をする人がおらず、比べる相手がいなかった。`,
    ],
  }),
  P({
    slug: 'consul-to-pe', area: 'consul',
    label: 'コンサルタント → PEファンド・投資',
    question: 'コンサルからPEファンドに移るのは現実的ですか。何を準備すればいいですか。',
    lead: '枠が極端に少なく、財務モデリングと投資の判断軸を自分で用意できているかが前提になる。ビジネスDDの経験があるかで入口が変わる。',
    before: { industry: 'コンサルティング', companies: ['戦略系コンサルティングファーム', '外資系コンサルティングファーム（総合）', '大手総合系コンサルティングファーム'], roles: ['コンサルタント', 'シニアコンサルタント', 'マネージャー'] },
    after: { industry: '投資・PE', companies: ['独立系PEファンド', '国内大手PEファンド', '投資会社', '事業再生ファンド'], roles: ['投資担当', 'アソシエイト', '投資先支援担当'] },
    age: [26, 38], income: [900, 1600], delta: [0, 500],
    motives: ['scope', 'income', 'domain'], barriers: ['industrygap', 'english', 'agefit'], breaks: ['study', 'narrow', 'reference'],
    incomeLogic: ['up_scarcity', 'up_role', 'up_stage'], takeaways: ['narrowfirst', 'income'],
    tags: ['PEファンド', 'ポストコンサル', '投資'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。ビジネスDDの案件に複数回入り、投資家側の視点に触れる機会があった。提言する側から、資本を持つ側に移りたいと考えた。`,
      (c) => `${c.years}年目の${c.beforeRole}。支援した企業のその後を追えないことが続き、腰を据えて1社に関わる働き方に関心が向いた。`,
    ],
  }),
  P({
    slug: 'erp-consultant', area: 'consul',
    label: 'SIer・事業会社 → ERP（SAP等）コンサルタント',
    question: 'ERPコンサルは今から目指す価値がありますか。年収はどのくらい変わりますか。',
    lead: '需要が読みやすく、経験年数がそのまま単価に乗りやすい領域。一方で、製品に閉じた専門性になるため、次の移動先を意識しておく必要がある。',
    before: { industry: 'SIer・事業会社', companies: ['大手SIer（メーカー系）', '中堅SIer', '東証プライム上場企業', '大手SIer（独立系）'], roles: ['業務システムのSE', '経理', '情報システム部門', '生産管理'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', 'ERP特化のコンサルティングファーム', '外資系コンサルティングファーム（総合）', 'IT系コンサルティングファーム'], roles: ['ERPコンサルタント', 'SAPコンサルタント', '業務コンサルタント'] },
    age: [25, 45], income: [450, 850], delta: [50, 350],
    motives: ['income', 'domain', 'skill'], barriers: ['certonly', 'nonum', 'narrowspec'], breaks: ['cert', 'domainbridge', 'number'],
    incomeLogic: ['up_shortage', 'up_scarcity', 'up_market'], takeaways: ['market', 'narrowfirst'],
    tags: ['ERP', 'SAP', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。基幹システムの導入プロジェクトに業務側として参加し、パッケージの考え方に触れた。`,
      (c) => `${c.years}年目の${c.beforeRole}。担当していた領域の求人を調べたところ、同じ業務知識でも立ち位置によって単価が大きく違うことを知った。`,
    ],
  }),
  P({
    slug: 'daini-shinsotsu-consul', area: 'consul',
    label: '第二新卒（20代前半） → コンサルタント',
    question: '社会人2〜3年目でコンサルに転職するのは早すぎますか。',
    lead: 'ポテンシャル採用の枠が使える最後の時期。実績よりも、地頭と学習の速さを示せるかで決まる。年収は一時的に下がることもある。',
    before: { industry: '各業界', companies: ['大手メーカー', '大手金融機関', '人材サービス企業', '大手小売企業'], roles: ['営業', '総合職', '企画職', '事務・管理'] },
    after: { industry: 'コンサルティング', companies: ['総合系コンサルティングファーム', 'IT系コンサルティングファーム', '国内独立系コンサルティングファーム', '外資系コンサルティングファーム（総合）'], roles: ['アナリスト', 'コンサルタント', 'ジュニアコンサルタント'] },
    age: [23, 27], income: [330, 550], delta: [-30, 250],
    motives: ['skill', 'evaluation', 'income'], barriers: ['nonum', 'nomanage', 'agefit'], breaks: ['casestudy', 'study', 'order'],
    incomeLogic: ['up_scope', 'flat_tradeoff', 'down_then_up'], takeaways: ['timing', 'order'],
    tags: ['第二新卒', '未経験からコンサル', '20代'],
    situations: [
      (c) => `${c.beforeCompany}に新卒で入社して${c.years}年目。仕事は覚えたが、この延長線上に自分が望むキャリアがあるかが見えなかった。動くなら早いほうがいいと考えた。`,
      (c) => `${c.years}年目の${c.beforeRole}。配属が希望と違い、身につくスキルが会社の中でしか使えないものだと感じていた。`,
    ],
  }),
  P({
    slug: 'senior-consul-to-komon', area: 'consul',
    label: '50代のファーム出身者 → 事業会社の顧問・経営幹部',
    question: '50代でファームを出た後、どんな選択肢がありますか。',
    lead: '正社員の枠は限られる一方で、顧問・社外取締役・非常勤といった関わり方の選択肢が広い。報酬より、関わる時間と決裁の範囲を先に決めるかどうかで進み方が変わる。',
    before: { industry: 'コンサルティング', companies: ['外資系コンサルティングファーム（総合）', '大手総合系コンサルティングファーム', '戦略系コンサルティングファーム', 'シンクタンク系コンサルティングファーム'], roles: ['パートナー', 'シニアマネージャー', 'ディレクター'] },
    after: { industry: '事業会社', companies: ['成長企業（上場準備中）', '東証プライム上場企業', '中堅の事業会社', 'シリーズCのSaaS企業'], roles: ['顧問', '経営企画責任者', '社外取締役', '事業責任者'] },
    age: [48, 58], income: [1200, 2200], delta: [-800, 0],
    motives: ['life', 'people', 'independence'], barriers: ['agefit', 'overqual', 'overspecialized'], breaks: ['narrow', 'reference', 'negotiate'],
    incomeLogic: ['down_life', 'flat_stage', 'down_then_up'], takeaways: ['tradeoff', 'income'],
    tags: ['50代', 'ポストコンサル', '顧問'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}まで務め、${c.years}年以上コンサルティングに従事した。${c.age}歳を迎え、支援する側ではなく、一つの会社に最後まで関わる形を考え始めた。`,
      (c) => `${c.years}年のキャリアの大半をファームで過ごした。${c.age}歳での次の一手として、フルタイムに限らない関わり方も含めて検討することにした。`,
    ],
  }),

  /* ================= M&A・FAS（追加4） ================= */
  P({
    slug: 'zeirishi-to-ma', area: 'ma',
    label: '税理士法人・会計事務所 → M&A仲介',
    question: '会計事務所からM&A業界に移れますか。中小企業の知識は活きますか。',
    lead: '中小企業のオーナーと直接話してきた経験が、そのまま案件の入口になる。決算書を読む力は前提として扱われ、評価されるのは提案に持ち込む力のほう。',
    before: { industry: '税理士法人・会計事務所', companies: ['大手税理士法人', '中堅会計事務所', '税理士法人（M&A部門なし）', '個人会計事務所'], roles: ['税務担当', '会計コンサルタント', '事業承継担当'] },
    after: { industry: 'M&A', companies: ['M&A仲介会社（上場）', 'M&Aブティック', '中堅M&A仲介会社', '独立系FA'], roles: ['M&Aアドバイザー', 'M&Aコンサルタント', '事業承継アドバイザー'] },
    age: [25, 42], income: [400, 750], delta: [50, 500],
    motives: ['income', 'scope', 'skill'], barriers: ['nonum', 'lowincome', 'industrygap'], breaks: ['domainbridge', 'number', 'mentor'],
    incomeLogic: ['up_stage', 'up_market', 'up_domain'], takeaways: ['market', 'bridge'],
    tags: ['M&A仲介', '会計事務所出身', '事業承継'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。顧問先から後継者の相談を受けることが増えていたが、自社で扱える範囲を超えていた。`,
      (c) => `${c.years}年、中小企業の税務を担当。オーナーとの距離は近かったが、提供できるサービスの幅が決まっていた。`,
    ],
  }),
  P({
    slug: 'ma-to-pe', area: 'ma',
    label: 'M&A仲介・FA → PEファンド',
    question: 'M&A仲介からPEファンドに移れますか。何が足りないと見られますか。',
    lead: '案件を成立させる力と、投資先を伸ばす力は別のものとして見られる。バリューアップの視点を持っているかが最大の確認点。',
    before: { industry: 'M&A', companies: ['M&A仲介会社（上場）', '独立系FA', 'M&Aブティック', '証券会社のIB部門'], roles: ['M&Aアドバイザー', 'FA（ファイナンシャルアドバイザー）', 'IBアナリスト'] },
    after: { industry: '投資・PE', companies: ['独立系PEファンド', '国内大手PEファンド', '投資会社', '事業再生ファンド'], roles: ['投資担当', 'アソシエイト', '投資先支援担当'] },
    age: [26, 40], income: [800, 1800], delta: [-200, 400],
    motives: ['domain', 'scope', 'skill'], barriers: ['industrygap', 'english', 'nomanage'], breaks: ['study', 'narrow', 'reference'],
    incomeLogic: ['up_scarcity', 'flat_tradeoff', 'up_role'], takeaways: ['narrowfirst', 'tradeoff'],
    tags: ['PEファンド', 'M&A', '投資'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。成約までは担当するが、その後の会社がどうなったかを知る機会がなかった。`,
      (c) => `${c.years}年で複数のディールを経験。取引を成立させること自体より、その後の価値をどう作るかに関心が移った。`,
    ],
  }),
  P({
    slug: 'jigyou-to-cvc', area: 'ma',
    label: '事業会社 → CVC・投資担当',
    question: '事業会社からCVCの投資担当になれますか。投資の経験がなくても大丈夫ですか。',
    lead: '事業とのシナジーを判断できることが役割の中心なので、投資経験より事業側の理解が優先されることが多い。設立初期のCVCほど入りやすい。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '大手サービス業', '大手通信企業'], roles: ['経営企画', '事業開発', '新規事業担当', 'アライアンス担当'] },
    after: { industry: '投資・CVC', companies: ['事業会社のCVC', '大手企業のコーポレートベンチャーキャピタル', '独立系VC', '投資会社'], roles: ['投資担当', 'キャピタリスト', '投資先支援担当'] },
    age: [27, 45], income: [600, 1100], delta: [0, 300],
    motives: ['scope', 'domain', 'skill'], barriers: ['industrygap', 'certonly', 'nonum'], breaks: ['study', 'domainbridge', 'mentor'],
    incomeLogic: ['up_scope', 'flat_stage', 'up_scarcity'], takeaways: ['bridge', 'narrowfirst'],
    tags: ['CVC', '投資', '事業開発'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。提携先の探索でスタートアップと接する機会が増え、投資の側から関わる仕事に関心を持った。`,
      (c) => `${c.beforeCompany}で${c.years}年目。新規事業の立ち上げを担当したが、自社で作るより外と組むほうが早い場面を何度も見てきた。`,
    ],
  }),
  P({
    slug: 'hoken-fudosan-to-ma', area: 'ma',
    label: '保険・不動産の営業 → M&A仲介',
    question: '保険や不動産の営業からM&A仲介に移れますか。',
    lead: '高単価・長期の商談を個人で完結させてきた経験がそのまま効く。財務の知識は入社後に埋める前提の会社が多く、入口は営業力で決まる。',
    before: { industry: '保険・不動産', companies: ['大手生命保険会社', '大手不動産会社', '不動産仲介会社', '損害保険会社'], roles: ['法人営業', '個人営業', '資産コンサルティング', '仲介営業'] },
    after: { industry: 'M&A', companies: ['M&A仲介会社（上場）', '中堅M&A仲介会社', 'M&Aブティック'], roles: ['M&Aアドバイザー', 'M&Aコンサルタント'] },
    age: [24, 38], income: [400, 900], delta: [-50, 500],
    motives: ['income', 'skill', 'scope'], barriers: ['industrygap', 'nonum', 'certonly'], breaks: ['number', 'study', 'domainbridge'],
    incomeLogic: ['up_stage', 'up_market', 'up_domain'], takeaways: ['market', 'income'],
    tags: ['M&A仲介', '営業出身', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。個人の数字は上位で安定していたが、扱う商品が決まっており、提案の幅に限界を感じていた。`,
      (c) => `${c.years}年間、経営者を相手にする営業を続けてきた。相談される内容が商品の外側に広がっていくのに、応えられる範囲が変わらなかった。`,
    ],
  }),

  /* ================= PM・PdM（追加5） ================= */
  P({
    slug: 'jyosys-to-pdm', area: 'pm',
    label: '社内SE・情報システム部門 → PdM',
    question: '情シスからプロダクトマネージャーになれますか。',
    lead: '要件を集めて優先順位をつける動きは日常的にやっている。足りないと見られるのは、事業の数字とプロダクトをつなげた経験。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '大手サービス業', '中堅IT企業'], roles: ['社内SE', '情報システム部門', 'IT企画', '業務改革担当'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', '中堅SaaS企業', 'シリーズCのSaaS企業'], roles: ['プロダクトマネージャー', 'PdM', '導入・カスタマーサクセス寄りのPdM'] },
    age: [26, 40], income: [450, 800], delta: [0, 250],
    motives: ['product', 'skill', 'income'], barriers: ['noselfdev', 'nonum', 'narrowspec'], breaks: ['number', 'domainbridge', 'portfolio'],
    incomeLogic: ['up_scope', 'up_domain', 'flat_tradeoff'], takeaways: ['bridge', 'evidence'],
    tags: ['PdM', '情シス', '未経験からPdM'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。社内の要望を集めて優先順位をつけ、ベンダーと仕様を詰める仕事を続けてきた。`,
      (c) => `${c.years}年間、${c.beforeRole}。使う人の顔が見える距離で仕事をしてきたが、作るのは常に外部だった。`,
    ],
  }),
  P({
    slug: 'designer-to-pdm', area: 'pm',
    label: 'デザイナー → PdM',
    question: 'デザイナーからPdMに移るとキャリアはどうなりますか。',
    lead: 'ユーザー体験の設計から入る移動。定性の理解は強い一方で、事業指標で意思決定した経験を問われる。',
    before: { industry: 'IT・デザイン', companies: ['上場SaaS企業', 'デジタルエージェンシー', 'シリーズBのSaaSスタートアップ', 'Web制作会社'], roles: ['UI/UXデザイナー', 'プロダクトデザイナー', 'アートディレクター'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', 'BtoCサービス企業', 'シリーズCのSaaS企業'], roles: ['プロダクトマネージャー', 'PdM', 'UXリード兼PdM'] },
    age: [26, 40], income: [450, 800], delta: [0, 250],
    motives: ['scope', 'product', 'income'], barriers: ['nonum', 'nomanage', 'noselfdev'], breaks: ['number', 'portfolio', 'reframe'],
    incomeLogic: ['up_scope', 'up_role', 'flat_tradeoff'], takeaways: ['evidence', 'reframe'],
    tags: ['PdM', 'デザイナー出身', 'UX'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。体験の設計には自信があったが、何を作るかの決定に最後まで関われないことが多かった。`,
      (c) => `${c.years}年目の${c.beforeRole}。ユーザー調査から設計まで担当する中で、優先順位を決める側に回りたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'pdm-to-cpo', area: 'pm',
    label: 'PdM → 事業責任者・CPO候補',
    question: 'PdMから事業責任者になるには何が必要ですか。',
    lead: 'プロダクトの成果だけでなく、損益に責任を持てるかが問われる。採用と組織づくりに関わった経験があるかで、見られ方が変わる。',
    before: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ'], roles: ['シニアプロダクトマネージャー', 'プロダクト責任者', 'グループPdM'] },
    after: { industry: 'SaaS・スタートアップ', companies: ['シリーズBのSaaSスタートアップ', 'シリーズCのSaaS企業', '上場準備中のスタートアップ', '上場SaaS企業'], roles: ['事業責任者', 'CPO候補', 'VPoP', '事業部長'] },
    age: [30, 45], income: [900, 1500], delta: [0, 400],
    motives: ['scope', 'people', 'independence'], barriers: ['nomanage', 'nonum', 'agefit'], breaks: ['number', 'reference', 'negotiate'],
    incomeLogic: ['up_role', 'up_stage', 'up_negotiation'], takeaways: ['income', 'reframe'],
    tags: ['CPO', 'PdM', '事業責任者'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。プロダクトの数字は伸ばしてきたが、価格や採用の判断は自分の範囲の外にあった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。${c.teamSize}名規模の組織でプロダクトを見てきたが、事業全体の損益を持つ経験がなかった。`,
    ],
  }),
  P({
    slug: 'gaishi-it-to-saas-pm', area: 'pm',
    label: '外資系IT → 国内SaaSのPM・PdM',
    question: '外資系ITから国内のSaaS企業に移るとどうなりますか。年収は下がりますか。',
    lead: '本社が作ったものを日本で売る側から、作る側へ。年収は下がることが多く、そのぶん決められる範囲が広がる交換になる。',
    before: { industry: '外資系IT', companies: ['外資系ソフトウェア企業の日本法人', '外資系クラウドベンダー', '外資系IT企業の日本法人'], roles: ['ソリューションアーキテクト', 'プロダクトスペシャリスト', 'カスタマーエンジニア', 'プリセールスエンジニア'] },
    after: { industry: 'SaaS・自社プロダクト', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', 'シリーズBのSaaSスタートアップ'], roles: ['プロダクトマネージャー', 'PdM', 'シニアプロダクトマネージャー'] },
    age: [28, 45], income: [800, 1500], delta: [-400, 100],
    motives: ['product', 'scope', 'culture'], barriers: ['overqual', 'noselfdev', 'customs'], breaks: ['negotiate', 'narrow', 'scope_down'],
    incomeLogic: ['down_life', 'flat_tradeoff', 'down_then_up'], takeaways: ['tradeoff', 'income'],
    tags: ['外資系', 'PdM', 'SaaS'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。製品の知識は深かったが、仕様を決めるのは本社であり、日本からの要望が反映されることは稀だった。`,
      (c) => `${c.years}年目の${c.beforeRole}。報酬と環境には不満がなかったが、売る側に留まり続けることへの疑問が大きくなった。`,
    ],
  }),
  P({
    slug: 'maker-kikaku-to-hardware-pm', area: 'pm',
    label: 'メーカーの商品企画 → ハードウェア・IoTのPM',
    question: 'メーカーの商品企画の経験は、スタートアップでも通用しますか。',
    lead: '量産と品質の勘所を持っている点が希少。一方で、開発の期間と意思決定の速さが大きく違うため、そこへの適応が論点になる。',
    before: { industry: 'メーカー', companies: ['大手電機メーカー', '大手家電メーカー', '大手部品メーカー', '大手精密機器メーカー'], roles: ['商品企画', 'プロダクトマネージャー', '設計開発', 'マーケティング'] },
    after: { industry: 'ハードウェア・IoT', companies: ['IoTプロダクト企業', 'シリーズBのハードウェアスタートアップ', '上場企業の新規プロダクト部門', 'D2Cプロダクト企業'], roles: ['プロダクトマネージャー', 'ハードウェアPM', '事業開発兼PM'] },
    age: [27, 45], income: [500, 900], delta: [-100, 250],
    motives: ['speed', 'scope', 'product'], barriers: ['bigco', 'customs', 'nonum'], breaks: ['scale', 'reframe', 'number'],
    incomeLogic: ['up_scope', 'flat_stage', 'down_then_up'], takeaways: ['reframe', 'tradeoff'],
    tags: ['ハードウェア', 'IoT', 'メーカー出身'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。年に一度の製品サイクルで企画から量産までを担当してきた。仕事は面白かったが、意思決定に関わる人が多すぎた。`,
      (c) => `${c.years}年目の${c.beforeRole}。市場の変化に対して、社内の開発サイクルが追いついていない実感があった。`,
    ],
  }),

  /* ================= エンジニア・IT（追加8） ================= */
  P({
    slug: 'frontend-to-jigyou', area: 'eng',
    label: '受託のフロントエンド → 事業会社の自社開発',
    question: '受託のフロントエンドから自社サービスに移れますか。',
    lead: '実装力は見えやすい一方で、リリース後に数字を見て直した経験があるかで評価が分かれる。作って納品する仕事との差はそこにある。',
    before: { industry: 'Web制作・受託開発', companies: ['Web制作会社', 'デジタルエージェンシー', '中堅の受託開発企業', 'SES企業'], roles: ['フロントエンドエンジニア', 'Webエンジニア', 'マークアップエンジニア'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ', 'BtoCサービス企業'], roles: ['フロントエンドエンジニア', 'ソフトウェアエンジニア', 'Webアプリケーションエンジニア'] },
    age: [23, 36], income: [350, 700], delta: [30, 280],
    motives: ['product', 'income', 'learning'], barriers: ['noselfdev', 'legacy', 'nonum'], breaks: ['portfolio', 'sidejob', 'study'],
    incomeLogic: ['up_scarcity', 'up_market', 'up_scope'], takeaways: ['proof', 'market'],
    tags: ['フロントエンド', '自社開発', 'ポートフォリオ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。案件は次々と回ってきたが、公開した後の数字を見る立場ではなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。使う技術が案件の予算で決まり、自分で選べないことが続いていた。`,
    ],
  }),
  P({
    slug: 'mobile-engineer-to-jigyou', area: 'eng',
    label: 'モバイルアプリエンジニア → 事業会社のプロダクト開発',
    question: 'アプリエンジニアの需要はまだありますか。どこへ移るのがいいですか。',
    lead: '受託でアプリを作る仕事と、自社アプリを伸ばす仕事では評価軸が違う。リテンションやクラッシュ率に責任を持った経験があるかが見られる。',
    before: { industry: 'IT・受託開発', companies: ['中堅の受託開発企業', 'アプリ開発会社', 'SES企業', 'Web制作会社'], roles: ['iOSエンジニア', 'Androidエンジニア', 'モバイルアプリエンジニア'] },
    after: { industry: 'IT・自社サービス', companies: ['大手Web企業', 'BtoCサービス企業', '上場SaaS企業', 'シリーズCのSaaS企業'], roles: ['モバイルアプリエンジニア', 'iOSエンジニア', 'テックリード'] },
    age: [24, 40], income: [400, 800], delta: [30, 280],
    motives: ['product', 'income', 'skill'], barriers: ['noselfdev', 'nonum', 'legacy'], breaks: ['portfolio', 'number', 'study'],
    incomeLogic: ['up_scarcity', 'up_scope', 'up_shortage'], takeaways: ['evidence', 'income'],
    tags: ['モバイルアプリ', '自社開発', 'iOS'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。納品して終わるアプリを作り続けてきたが、育てる経験がなかった。`,
      (c) => `${c.years}年目の${c.beforeRole}。クライアントの要望どおりに作ることが評価の全てで、使われ方を根拠に提案する機会がなかった。`,
    ],
  }),
  P({
    slug: 'soc-to-security-consul', area: 'eng',
    label: 'セキュリティ運用（SOC） → セキュリティコンサル・事業会社のCSIRT',
    question: 'SOCの監視業務から、その先のキャリアはどうなりますか。',
    lead: '監視の経験は前提として扱われ、評価されるのは「検知の先」に関わったかどうか。インシデント対応と、その後の再発防止まで見た経験が効く。',
    before: { industry: 'セキュリティ・SIer', companies: ['セキュリティ専門企業', '大手SIer（独立系）', 'MSSP事業者', 'SES企業'], roles: ['SOCアナリスト', 'セキュリティ監視', 'セキュリティエンジニア'] },
    after: { industry: 'セキュリティ・事業会社', companies: ['総合系コンサルティングファーム', '東証プライム上場企業', '上場SaaS企業', 'セキュリティ専門企業'], roles: ['セキュリティコンサルタント', 'CSIRT担当', 'セキュリティエンジニア（事業会社）'] },
    age: [24, 42], income: [400, 800], delta: [50, 300],
    motives: ['scope', 'income', 'learning'], barriers: ['narrowspec', 'nonum', 'certonly'], breaks: ['reframe', 'cert', 'number'],
    incomeLogic: ['up_shortage', 'up_scarcity', 'up_scope'], takeaways: ['reframe', 'market'],
    tags: ['セキュリティ', 'SOC', 'CSIRT'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。シフト勤務でアラートを捌く日々で、判断の裁量は手順書の範囲に限られていた。`,
      (c) => `${c.years}年間、監視業務に従事。検知はできても、そこから先の対応と改善は別の部署の仕事だった。`,
    ],
  }),
  P({
    slug: 'jyosys-to-corporate-it', area: 'eng',
    label: '情シス → 成長企業のコーポレートIT・IT基盤',
    question: '情シスの経験を活かして年収を上げるには、どこへ移ればいいですか。',
    lead: '同じ情シスでも、コストセンター扱いの組織と、事業成長の前提として投資される組織では報酬水準が違う。何を任されていたかより、どこに置かれていたかが効く。',
    before: { industry: '事業会社', companies: ['大手メーカー', '東証プライム上場企業', '中堅の事業会社', '大手小売企業'], roles: ['情報システム部門', '社内SE', 'IT基盤担当', '情シスマネージャー'] },
    after: { industry: '成長企業・SaaS', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', '成長企業（上場準備中）', '大手Web企業'], roles: ['コーポレートIT', 'IT基盤エンジニア', '情報システム責任者', 'ITマネージャー'] },
    age: [26, 45], income: [420, 800], delta: [50, 300],
    motives: ['income', 'evaluation', 'scope'], barriers: ['narrowspec', 'nonum', 'legacy'], breaks: ['number', 'reframe', 'study'],
    incomeLogic: ['up_market', 'up_scope', 'up_role'], takeaways: ['market', 'income'],
    tags: ['情シス', 'コーポレートIT', '年収'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。全社のIT環境を1人で見る立場だったが、間接部門として扱われ評価にも上限があった。`,
      (c) => `${c.years}年間、社内のIT基盤を担当。やっていることの範囲は広かったが、社内では「困ったときに呼ばれる人」だった。`,
    ],
  }),
  P({
    slug: 'game-to-saas-engineer', area: 'eng',
    label: 'ゲーム業界のエンジニア → SaaS・Web',
    question: 'ゲーム業界から一般のIT企業に移れますか。経験は評価されますか。',
    lead: '負荷の高い環境での実装力は評価される。一方で、使ってきた技術と開発の進め方が特殊なため、共通言語に翻訳する作業が必要になる。',
    before: { industry: 'ゲーム', companies: ['大手ゲーム会社', 'ソーシャルゲーム企業', 'ゲーム開発会社', 'モバイルゲーム企業'], roles: ['サーバーサイドエンジニア', 'クライアントエンジニア', 'ゲームプログラマー'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズCのSaaS企業', 'シリーズBのSaaSスタートアップ'], roles: ['バックエンドエンジニア', 'ソフトウェアエンジニア', 'テックリード'] },
    age: [25, 40], income: [450, 850], delta: [-50, 250],
    motives: ['work', 'life', 'skill'], barriers: ['legacy', 'customs', 'narrowspec'], breaks: ['reframe', 'portfolio', 'study'],
    incomeLogic: ['flat_tradeoff', 'up_scope', 'up_scarcity'], takeaways: ['reframe', 'tradeoff'],
    tags: ['ゲーム業界', '自社開発', 'キャリアチェンジ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。技術的には難しい仕事をしていたが、リリース前の稼働の波が読めず、生活の設計が難しかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。タイトルの当たり外れで組織ごと変わる環境が続き、積み上げが効く場所に移りたいと考えた。`,
    ],
  }),
  P({
    slug: 'kenkyu-to-engineer', area: 'eng',
    label: '研究職・アカデミア → ソフトウェアエンジニア',
    question: '研究職からエンジニアに転職できますか。年齢的に不利でしょうか。',
    lead: '課題を定義して検証する力は強い。足りないと見られるのは、動くものを他人と一緒に作り続ける経験のほう。',
    before: { industry: '研究・アカデミア', companies: ['大学・大学院', '公的研究機関', '大手メーカーの研究所', '博士課程'], roles: ['研究員', 'ポスドク', '研究開発', '大学院生'] },
    after: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズBのSaaSスタートアップ', '事業会社の内製開発組織'], roles: ['ソフトウェアエンジニア', 'バックエンドエンジニア', '研究開発エンジニア'] },
    age: [26, 40], income: [350, 700], delta: [0, 350],
    motives: ['income', 'future', 'skill'], barriers: ['nohandson', 'agefit', 'customs'], breaks: ['portfolio', 'sidejob', 'study'],
    incomeLogic: ['up_market', 'up_scope', 'up_scarcity'], takeaways: ['proof', 'market'],
    tags: ['研究職', '未経験からエンジニア', 'キャリアチェンジ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。研究そのものには手応えがあったが、ポストの見通しが立たなかった。`,
      (c) => `${c.years}年、研究に従事。実装は道具として使ってきたが、チームで開発した経験はほとんどなかった。`,
    ],
  }),
  P({
    slug: 'engineer-to-cto', area: 'eng',
    label: 'エンジニア → スタートアップのCTO・VPoE',
    question: 'スタートアップのCTOになるには何が必要ですか。',
    lead: '技術力より、採用と技術選定の意思決定を任せられるかで判断される。少人数のフェーズでは、自分で書けることも同時に求められる。',
    before: { industry: 'IT・自社サービス', companies: ['上場SaaS企業', '大手Web企業', 'シリーズCのSaaS企業', '受託開発企業'], roles: ['テックリード', 'エンジニアリングマネージャー', 'シニアエンジニア'] },
    after: { industry: 'スタートアップ', companies: ['シードのスタートアップ', 'シリーズAのスタートアップ', 'シリーズBのスタートアップ'], roles: ['CTO', 'VPoE', '開発責任者'] },
    age: [28, 45], income: [700, 1200], delta: [-300, 200],
    motives: ['scope', 'independence', 'people'], barriers: ['nomanage', 'overqual', 'nohandson'], breaks: ['trial', 'reference', 'negotiate'],
    incomeLogic: ['up_stage', 'down_then_up', 'flat_stage'], takeaways: ['tradeoff', 'income'],
    tags: ['CTO', 'スタートアップ', 'エンジニア'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。整った組織の中で技術的な意思決定を担ってきたが、ゼロから作った経験はなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。${c.teamSize}名の開発組織を見る立場になり、次は事業と技術の両方に責任を持つ役割に関心が向いた。`,
    ],
  }),
  P({
    slug: 'embedded-to-sdv', area: 'eng',
    label: '組込みエンジニア → 車載ソフト・SDV',
    question: '組込みの経験を、成長している領域で活かすにはどこへ行けばいいですか。',
    lead: '同じ組込みでも、ソフトウェアが製品価値の中心になっている領域では報酬水準が違う。既存の技術がそのまま効きやすい移動。',
    before: { industry: 'メーカー・組込み', companies: ['大手部品メーカー', '中堅の組込み受託企業', '大手電機メーカー', '大手自動車部品メーカー'], roles: ['組込みソフトウェアエンジニア', '制御ソフト開発', 'ファームウェアエンジニア'] },
    after: { industry: '車載・モビリティ', companies: ['大手自動車メーカー', '車載ソフトウェア企業', 'モビリティスタートアップ', '外資系ティア1サプライヤー'], roles: ['車載ソフトウェアエンジニア', 'ソフトウェアアーキテクト', '制御開発エンジニア'] },
    age: [26, 45], income: [450, 900], delta: [50, 300],
    motives: ['income', 'future', 'skill'], barriers: ['legacy', 'narrowspec', 'english'], breaks: ['study', 'reframe', 'number'],
    incomeLogic: ['up_market', 'up_shortage', 'up_scarcity'], takeaways: ['market', 'reframe'],
    tags: ['組込み', '車載', 'モビリティ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。担当製品の開発サイクルは長く、新しい技術に触れる機会が限られていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。自社の主力製品が中長期でどうなるかを考えたとき、同じ技術でも置き場所を変えたほうがいいと判断した。`,
    ],
  }),

  /* ================= データ・AI（新領域5） ================= */
  P({
    slug: 'analyst-to-datascientist', area: 'data',
    label: '事業会社のアナリスト → データサイエンティスト',
    question: '事業会社の分析担当からデータサイエンティストになれますか。',
    lead: '事業の文脈を理解している点が最大の強み。統計や機械学習の知識より、意思決定に効いた分析をしたことがあるかで判断される。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手小売企業', '大手サービス業', '中堅IT企業'], roles: ['データアナリスト', '営業企画', 'マーケティング分析', '経営管理'] },
    after: { industry: 'IT・データ', companies: ['上場SaaS企業', '大手Web企業', 'シリーズCのSaaS企業', 'データ分析支援企業'], roles: ['データサイエンティスト', 'データアナリスト', 'アナリティクスエンジニア'] },
    age: [25, 40], income: [420, 800], delta: [30, 300],
    motives: ['skill', 'income', 'learning'], barriers: ['certonly', 'nohandson', 'nonum'], breaks: ['portfolio', 'study', 'number'],
    incomeLogic: ['up_market', 'up_scarcity', 'up_scope'], takeaways: ['proof', 'market'],
    tags: ['データサイエンティスト', '分析', '未経験から'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。集計と資料作成が業務の大半で、分析の結果が意思決定に届く前に止まることが多かった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。独学で機械学習を学んでいたが、実務で使う機会が社内になかった。`,
    ],
  }),
  P({
    slug: 'engineer-to-data-engineer', area: 'data',
    label: 'エンジニア → データエンジニア（データ基盤）',
    question: 'アプリケーションエンジニアからデータ基盤の仕事に移れますか。',
    lead: '需要に対して経験者が少なく、隣接職種からの移動が成立しやすい。SQLとパイプラインの設計経験があるかが最初の確認点。',
    before: { industry: 'IT・SIer', companies: ['大手SIer（独立系）', '上場SaaS企業', '中堅の受託開発企業', '事業会社の内製開発組織'], roles: ['バックエンドエンジニア', 'システムエンジニア', 'インフラエンジニア', 'DBエンジニア'] },
    after: { industry: 'IT・データ', companies: ['上場SaaS企業', '大手Web企業', 'シリーズCのSaaS企業', 'データ分析支援企業'], roles: ['データエンジニア', 'アナリティクスエンジニア', 'データ基盤エンジニア'] },
    age: [25, 42], income: [450, 850], delta: [50, 300],
    motives: ['skill', 'income', 'domain'], barriers: ['nohandson', 'narrowspec', 'legacy'], breaks: ['portfolio', 'study', 'number'],
    incomeLogic: ['up_shortage', 'up_scarcity', 'up_market'], takeaways: ['market', 'narrowfirst'],
    tags: ['データエンジニア', 'データ基盤', 'キャリアチェンジ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。集計基盤の構築を一部担当したことがきっかけで、データ側に関心が向いた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。アプリケーション開発の求人は多いが単価の伸びが読めず、隣接する領域を調べ始めた。`,
    ],
  }),
  P({
    slug: 'researcher-to-ml-engineer', area: 'data',
    label: '研究職 → 機械学習エンジニア',
    question: '研究の経験を活かして機械学習エンジニアになれますか。',
    lead: 'モデルを作る力より、動く形にして運用に乗せた経験が問われる。論文と実装の両方を持っている人は少なく、評価は高い。',
    before: { industry: '研究・アカデミア', companies: ['大学・大学院', '公的研究機関', '大手メーカーの研究所', '博士課程'], roles: ['研究員', 'ポスドク', '研究開発', 'データ解析担当'] },
    after: { industry: 'IT・AI', companies: ['AI開発企業', '大手Web企業', '上場SaaS企業', 'シリーズBのAIスタートアップ'], roles: ['機械学習エンジニア', 'MLエンジニア', 'リサーチエンジニア'] },
    age: [26, 42], income: [400, 800], delta: [50, 400],
    motives: ['income', 'future', 'product'], barriers: ['nohandson', 'customs', 'agefit'], breaks: ['portfolio', 'sidejob', 'study'],
    incomeLogic: ['up_market', 'up_scarcity', 'up_shortage'], takeaways: ['proof', 'market'],
    tags: ['機械学習', '研究職', 'AI'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。研究の質には自信があったが、成果が実用に届くまでの距離が遠かった。`,
      (c) => `${c.years}年、研究に従事。手を動かす力はあったが、本番環境で動かし続ける経験がなかった。`,
    ],
  }),
  P({
    slug: 'ml-to-llm-product', area: 'data',
    label: '機械学習エンジニア → 生成AI・LLMプロダクト',
    question: '生成AI関連のポジションに移るには何が必要ですか。',
    lead: '経験者がほとんどいない領域なので、隣接する経験と、自分で試した量が判断材料になる。動くものを作った履歴が最も強い。',
    before: { industry: 'IT・データ', companies: ['大手Web企業', '上場SaaS企業', 'AI開発企業', 'データ分析支援企業'], roles: ['機械学習エンジニア', 'データサイエンティスト', 'MLエンジニア', 'バックエンドエンジニア'] },
    after: { industry: 'AI・SaaS', companies: ['シリーズBのAIスタートアップ', '上場SaaS企業', 'シリーズAのスタートアップ', '大手Web企業'], roles: ['LLMエンジニア', 'AIプロダクトエンジニア', 'MLエンジニア', 'AI活用推進担当'] },
    age: [25, 42], income: [550, 1000], delta: [50, 400],
    motives: ['skill', 'future', 'speed'], barriers: ['noportfolio', 'legacy', 'nonum'], breaks: ['sidejob', 'portfolio', 'study'],
    incomeLogic: ['up_shortage', 'up_scarcity', 'up_market'], takeaways: ['proof', 'market'],
    tags: ['生成AI', 'LLM', '機械学習'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。既存の分析業務は回せていたが、社内で新しい技術を試す余地がほとんどなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。個人で試している内容と、業務で求められる内容の差が広がっていた。`,
    ],
  }),
  P({
    slug: 'marketing-to-data-analyst', area: 'data',
    label: 'マーケティング・営業企画 → データアナリスト',
    question: 'マーケの経験からデータ分析の仕事に移れますか。',
    lead: '事業の問いを立てられることが強み。SQLが書けるかどうかが最初の足切りになるので、そこだけは先に埋めておく必要がある。',
    before: { industry: 'マーケティング・事業会社', companies: ['広告代理店', '東証プライム上場企業', 'BtoCサービス企業', '大手小売企業'], roles: ['マーケティング', '営業企画', '販促企画', 'デジタルマーケティング'] },
    after: { industry: 'IT・データ', companies: ['上場SaaS企業', '大手Web企業', 'BtoCサービス企業', 'シリーズCのSaaS企業'], roles: ['データアナリスト', 'マーケティングアナリスト', 'プロダクトアナリスト'] },
    age: [24, 38], income: [400, 700], delta: [0, 250],
    motives: ['skill', 'income', 'learning'], barriers: ['nohandson', 'certonly', 'nonum'], breaks: ['study', 'portfolio', 'number'],
    incomeLogic: ['up_scope', 'up_market', 'flat_tradeoff'], takeaways: ['proof', 'bridge'],
    tags: ['データアナリスト', 'マーケティング', 'SQL'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。施策の効果を測る場面で、いつも他部署に数字を依頼していた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。自分で数字を出せないことが、提案の速さと精度の両方を制約していた。`,
    ],
  }),

  /* ================= 営業・カスタマーサクセス（新領域6） ================= */
  P({
    slug: 'is-to-fs', area: 'sales',
    label: 'インサイドセールス → フィールドセールス',
    question: 'インサイドセールスから外勤の営業に移れますか。',
    lead: '同じ営業組織の中の役割変更に見えるが、評価される指標が「商談の数」から「受注の金額」に変わる。案件を自分で締めた経験があるかが分かれ目。',
    before: { industry: 'SaaS・IT', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', '中堅SaaS企業', '大手IT企業'], roles: ['インサイドセールス', 'SDR', 'BDR'] },
    after: { industry: 'SaaS・IT', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', 'シリーズBのSaaSスタートアップ', '中堅SaaS企業'], roles: ['フィールドセールス', 'アカウントエグゼクティブ', 'エンタープライズセールス'] },
    age: [23, 34], income: [350, 650], delta: [30, 250],
    motives: ['scope', 'income', 'skill'], barriers: ['nonum', 'agefit', 'nomanage'], breaks: ['number', 'internal', 'reframe'],
    incomeLogic: ['up_scope', 'up_role', 'up_market'], takeaways: ['inside', 'reframe'],
    tags: ['インサイドセールス', 'SaaS営業', 'キャリアアップ'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。商談化の数字は安定して達成していたが、その先の受注は別の担当が持っていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。社内でのフィールドセールスへの異動枠が埋まっており、外での機会を探すことにした。`,
    ],
  }),
  P({
    slug: 'sales-to-saas-sales', area: 'sales',
    label: '有形・無形商材の営業 → SaaS営業',
    question: '一般的な法人営業からSaaS営業に移れますか。年収は上がりますか。',
    lead: '売り方の型が大きく違う。飛び込みや関係構築で数字を作ってきた人ほど、分業と数値管理の文化への適応が論点になる。',
    before: { industry: '営業', companies: ['大手メーカー', '人材サービス企業', '広告代理店', '大手商社'], roles: ['法人営業', 'ソリューション営業', 'ルート営業'] },
    after: { industry: 'SaaS', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', 'シリーズCのSaaS企業', '中堅SaaS企業'], roles: ['フィールドセールス', 'アカウントエグゼクティブ', 'インサイドセールス'] },
    age: [23, 38], income: [380, 750], delta: [0, 280],
    motives: ['income', 'skill', 'future'], barriers: ['industrygap', 'customs', 'nonum'], breaks: ['study', 'number', 'mentor'],
    incomeLogic: ['up_market', 'up_scope', 'flat_tradeoff'], takeaways: ['market', 'bridge'],
    tags: ['SaaS営業', '営業出身', '未経験から'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。数字は作れていたが、売っているものが伸びている市場かどうかに不安があった。`,
      (c) => `${c.years}年目の${c.beforeRole}。同世代でSaaSに移った知人の話を聞き、営業の進め方が根本的に違うことを知った。`,
    ],
  }),
  P({
    slug: 'sales-to-sales-manager', area: 'sales',
    label: 'SaaS営業 → 営業マネージャー・営業責任者',
    question: 'プレイヤーからマネージャーになるとき、何が見られますか。',
    lead: '自分の数字ではなく、他人の数字を作った経験が問われる。育成した人数と、その人の成果の変化を語れるかで評価が変わる。',
    before: { industry: 'SaaS', companies: ['上場SaaS企業', 'シリーズCのSaaS企業', 'シリーズBのSaaSスタートアップ', '中堅SaaS企業'], roles: ['フィールドセールス', 'アカウントエグゼクティブ', 'チームリーダー'] },
    after: { industry: 'SaaS・スタートアップ', companies: ['シリーズBのSaaSスタートアップ', '上場SaaS企業', '成長企業（上場準備中）', 'シリーズCのSaaS企業'], roles: ['営業マネージャー', 'セールス責任者', '事業部長候補'] },
    age: [26, 42], income: [500, 950], delta: [30, 350],
    motives: ['people', 'income', 'scope'], barriers: ['nomanage', 'nonum', 'agefit'], breaks: ['number', 'reference', 'negotiate'],
    incomeLogic: ['up_role', 'up_scope', 'up_negotiation'], takeaways: ['reframe', 'income'],
    tags: ['営業マネージャー', 'SaaS営業', 'マネジメント'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。個人の予算は達成し続けていたが、マネージャーの枠が空く見込みがなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。後輩の指導を任される機会が増え、人を通して数字を作る側に関心が向いた。`,
    ],
  }),
  P({
    slug: 'cs-to-cs-manager', area: 'sales',
    label: 'カスタマーサクセス → CS責任者・組織立ち上げ',
    question: 'CSのキャリアはどこへ向かいますか。',
    lead: '個社対応の巧さではなく、仕組みで継続率を上げた経験が評価される。オンボーディングの型を作った実績があるかが分かれ目。',
    before: { industry: 'SaaS', companies: ['上場SaaS企業', 'シリーズBのSaaSスタートアップ', '中堅SaaS企業', 'シリーズCのSaaS企業'], roles: ['カスタマーサクセス', 'オンボーディング担当', 'CSチームリーダー'] },
    after: { industry: 'SaaS・スタートアップ', companies: ['シリーズBのSaaSスタートアップ', 'シリーズAのスタートアップ', '上場SaaS企業', '成長企業（上場準備中）'], roles: ['CS責任者', 'カスタマーサクセスマネージャー', 'CS組織の立ち上げ担当'] },
    age: [25, 42], income: [420, 850], delta: [30, 300],
    motives: ['scope', 'people', 'income'], barriers: ['nomanage', 'nonum', 'toomanyroles'], breaks: ['number', 'reframe', 'story'],
    incomeLogic: ['up_role', 'up_stage', 'up_scope'], takeaways: ['reframe', 'income'],
    tags: ['カスタマーサクセス', 'SaaS', 'マネジメント'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。担当顧客の継続率は高かったが、それが自分の対応によるものか仕組みによるものか説明できなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。CS組織が大きくなる過程で、型を作る側に回りたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'sales-to-partner-alliance', area: 'sales',
    label: '営業 → パートナーセールス・アライアンス',
    question: '直販の営業からパートナー営業に移るとどう変わりますか。',
    lead: '自分で売る仕事から、売ってもらう仕組みを作る仕事へ。短期の数字が動きにくいぶん、成果の説明の仕方を変える必要がある。',
    before: { industry: 'IT・SaaS', companies: ['上場SaaS企業', '大手IT企業', '中堅SaaS企業', '大手SIer（独立系）'], roles: ['フィールドセールス', '法人営業', 'アカウントエグゼクティブ'] },
    after: { industry: 'SaaS・外資系IT', companies: ['上場SaaS企業', '外資系ソフトウェア企業の日本法人', 'シリーズCのSaaS企業', '大手IT企業'], roles: ['パートナーセールス', 'アライアンス担当', 'チャネルマネージャー'] },
    age: [26, 45], income: [500, 950], delta: [0, 300],
    motives: ['scope', 'skill', 'income'], barriers: ['nonum', 'coordinator', 'nomanage'], breaks: ['reframe', 'number', 'ask'],
    incomeLogic: ['up_scope', 'up_role', 'flat_stage'], takeaways: ['reframe', 'tradeoff'],
    tags: ['パートナーセールス', 'アライアンス', 'SaaS'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。直販の数字は作れたが、1人で届く範囲には限りがあった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。代理店経由の案件に関わる中で、仕組みで売上を作る側の仕事に関心を持った。`,
    ],
  }),
  P({
    slug: 'kokunai-to-gaishi-sales', area: 'sales',
    label: '国内企業の営業 → 外資系IT営業',
    question: '外資系IT企業の営業に移ると、年収と働き方はどう変わりますか。',
    lead: '固定給と歩合の比率が変わり、達成できれば水準は大きく上がる。一方で、目標未達が続いたときの扱いも変わるので、その前提込みの判断になる。',
    before: { industry: 'IT・事業会社', companies: ['大手SIer（独立系）', '上場SaaS企業', '大手IT企業', '中堅IT企業'], roles: ['法人営業', 'ソリューション営業', 'アカウントエグゼクティブ'] },
    after: { industry: '外資系IT', companies: ['外資系ソフトウェア企業の日本法人', '外資系クラウドベンダー', '外資系IT企業の日本法人'], roles: ['アカウントエグゼクティブ', 'エンタープライズセールス', 'インダストリー営業'] },
    age: [27, 45], income: [550, 1100], delta: [50, 500],
    motives: ['income', 'skill', 'global'], barriers: ['english', 'customs', 'nonum'], breaks: ['study', 'number', 'mentor'],
    incomeLogic: ['up_market', 'up_stage', 'up_negotiation'], takeaways: ['market', 'tradeoff'],
    tags: ['外資系', '営業', '年収'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。成果は出していたが、報酬に反映される幅が制度で決まっていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。同じ商材を扱う外資系企業の担当者と会う機会があり、報酬体系の違いを知った。`,
    ],
  }),

  /* ================= コーポレート・管理部門（新領域5） ================= */
  P({
    slug: 'keiri-to-fpa', area: 'corp',
    label: '経理 → 経営管理・FP&A',
    question: '経理から経営管理やFP&Aに移れますか。',
    lead: '過去の数字を締める仕事から、先の数字を作る仕事へ。決算の正確さではなく、予測と説明ができるかで評価される。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '中堅の事業会社', '大手サービス業'], roles: ['経理', '財務会計', '連結決算担当', '税務担当'] },
    after: { industry: '事業会社・SaaS', companies: ['上場SaaS企業', '成長企業（上場準備中）', '東証プライム上場企業', 'シリーズCのSaaS企業'], roles: ['経営管理', 'FP&A', '経営企画（財務）', '管理会計担当'] },
    age: [25, 42], income: [420, 800], delta: [30, 280],
    motives: ['scope', 'skill', 'income'], barriers: ['narrowspec', 'nonum', 'certonly'], breaks: ['reframe', 'internal', 'number'],
    incomeLogic: ['up_scope', 'up_role', 'up_market'], takeaways: ['reframe', 'inside'],
    tags: ['経理', 'FP&A', '経営管理'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。月次と年次の締めを正確に回してきたが、その数字が経営の判断にどう使われたかは見えなかった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。会計の知識は積み上がったが、事業側と話す機会がほとんどなかった。`,
    ],
  }),
  P({
    slug: 'houmu-to-startup-houmu', area: 'corp',
    label: '法務 → スタートアップの法務・法務責任者',
    question: '大企業の法務からスタートアップに移るとどうなりますか。',
    lead: '契約審査の専門家から、事業を進めるための判断をする役割へ。前例のない論点に自分で答えを出せるかが問われる。',
    before: { industry: '事業会社・法律事務所', companies: ['東証プライム上場企業', '大手メーカー', '法律事務所', '大手金融機関'], roles: ['法務', '契約審査', 'コンプライアンス', '企業内弁護士'] },
    after: { industry: 'スタートアップ', companies: ['シリーズBのスタートアップ', '上場準備中のスタートアップ', 'シリーズCのSaaS企業', '成長企業（上場準備中）'], roles: ['法務責任者', '法務マネージャー', 'コーポレート責任者'] },
    age: [27, 45], income: [500, 950], delta: [-100, 250],
    motives: ['scope', 'speed', 'people'], barriers: ['narrowspec', 'nomanage', 'customs'], breaks: ['reframe', 'ask', 'mentor'],
    incomeLogic: ['up_scope', 'flat_stage', 'up_role'], takeaways: ['reframe', 'tradeoff'],
    tags: ['法務', 'スタートアップ', 'コーポレート'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。分業が進んだ組織で、担当する契約の類型が決まっていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。リスクを指摘する役割に偏り、事業を前に進める側の判断に関わりたいと考えるようになった。`,
    ],
  }),
  P({
    slug: 'jinji-soumu-to-corp-lead', area: 'corp',
    label: '人事・総務 → コーポレート責任者',
    question: 'バックオフィス全般を見る立場になるには、どんな移動が必要ですか。',
    lead: '成長企業では、人事・総務・法務・経理を一人で見る役割が生まれる。専門の深さより、優先順位をつけて回した経験が評価される。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '中堅の事業会社', '大手サービス業', '人材サービス企業'], roles: ['人事', '総務', '労務', '人事総務マネージャー'] },
    after: { industry: 'スタートアップ・成長企業', companies: ['シリーズBのスタートアップ', '成長企業（上場準備中）', 'シリーズCのSaaS企業', '上場準備中のスタートアップ'], roles: ['コーポレート責任者', '管理部門マネージャー', '人事責任者'] },
    age: [27, 45], income: [420, 850], delta: [0, 280],
    motives: ['scope', 'people', 'income'], barriers: ['toomanyroles', 'nonum', 'nomanage'], breaks: ['story', 'number', 'reframe'],
    incomeLogic: ['up_role', 'up_stage', 'up_scope'], takeaways: ['reframe', 'income'],
    tags: ['コーポレート', '人事', '管理部門'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。分業された組織の中で、担当する領域が細かく決まっていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。制度の運用が中心で、作る側に回る機会がほとんどなかった。`,
    ],
  }),
  P({
    slug: 'koho-pr-to-startup', area: 'corp',
    label: '広報・PR → スタートアップの広報',
    question: '大企業の広報からスタートアップの広報に移れますか。',
    lead: '守りの広報から、認知を作る攻めの広報へ。メディアとの関係より、何を打ち出すかを自分で決めた経験が評価される。',
    before: { industry: '事業会社・PR会社', companies: ['東証プライム上場企業', 'PR会社', '大手メーカー', '広告代理店'], roles: ['広報', 'PR担当', 'コーポレートコミュニケーション', '広報マネージャー'] },
    after: { industry: 'スタートアップ', companies: ['シリーズBのスタートアップ', 'シリーズCのSaaS企業', '上場準備中のスタートアップ', 'シリーズAのスタートアップ'], roles: ['広報責任者', 'PRマネージャー', 'コミュニケーション担当'] },
    age: [25, 42], income: [400, 800], delta: [-50, 250],
    motives: ['scope', 'speed', 'product'], barriers: ['nonum', 'toomanyroles', 'bigco'], breaks: ['number', 'reframe', 'story'],
    incomeLogic: ['up_scope', 'flat_stage', 'up_role'], takeaways: ['reframe', 'tradeoff'],
    tags: ['広報', 'PR', 'スタートアップ'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。リリースの作成と取材対応が中心で、発信の方針は上位で決まっていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。守りの広報が業務の大半を占め、認知を作る仕事に関わりたいと考えた。`,
    ],
  }),
  P({
    slug: 'keiri-to-ipo', area: 'corp',
    label: '経理 → IPO準備・上場企業の経理',
    question: 'IPO準備の経験がなくても、上場準備中の会社に入れますか。',
    lead: '経験者が少なく、上場企業での実務があれば入口になる。監査法人・主幹事とのやり取りを自分で回せるかが問われる。',
    before: { industry: '事業会社・監査法人', companies: ['東証プライム上場企業', '大手監査法人', '中堅の事業会社', '大手メーカー'], roles: ['経理', '連結決算担当', '開示担当', '会計監査'] },
    after: { industry: 'スタートアップ・成長企業', companies: ['上場準備中のスタートアップ', '成長企業（上場準備中）', 'シリーズCのSaaS企業', 'シリーズBのスタートアップ'], roles: ['IPO準備担当', '経理マネージャー', '管理部門責任者', '経営管理'] },
    age: [26, 45], income: [450, 900], delta: [0, 300],
    motives: ['scope', 'skill', 'income'], barriers: ['certonly', 'nomanage', 'narrowspec'], breaks: ['reframe', 'study', 'mentor'],
    incomeLogic: ['up_scarcity', 'up_role', 'up_stage'], takeaways: ['narrowfirst', 'income'],
    tags: ['IPO', '経理', 'スタートアップ'],
    situations: [
      (c) => `${c.beforeCompany}の${c.beforeRole}として${c.years}年。上場企業の開示実務を担当してきたが、制度が既に整った状態での運用だった。`,
      (c) => `${c.beforeCompany}で${c.years}年目。整備された仕組みを回す側から、仕組みを作る側に移りたいと考えるようになった。`,
    ],
  }),

  /* ================= 事業開発・経営企画（追加1） ================= */
  P({
    slug: 'jigyou-to-shinki-jigyou', area: 'biz',
    label: '事業会社 → 新規事業開発',
    question: '既存事業の担当から新規事業に移るには何が必要ですか。',
    lead: '整った事業を回す力と、無いものを立ち上げる力は別に見られる。社内で小さくても立ち上げた経験があるかが判断材料になる。',
    before: { industry: '事業会社', companies: ['東証プライム上場企業', '大手メーカー', '大手サービス業', '大手小売企業'], roles: ['営業', '事業部門の企画', 'マーケティング', '経営企画'] },
    after: { industry: '事業会社・スタートアップ', companies: ['東証プライム上場企業', 'シリーズBのスタートアップ', '成長企業（上場準備中）', '上場SaaS企業'], roles: ['新規事業開発', '事業開発', '新規事業責任者'] },
    age: [26, 44], income: [450, 900], delta: [0, 300],
    motives: ['scope', 'independence', 'speed'], barriers: ['bigco', 'nonum', 'toomanyroles'], breaks: ['internal', 'number', 'story'],
    incomeLogic: ['up_scope', 'up_role', 'flat_stage'], takeaways: ['inside', 'reframe'],
    tags: ['新規事業', '事業開発', '事業会社'],
    situations: [
      (c) => `${c.beforeCompany}で${c.beforeRole}として${c.years}年。既存事業の数字は作れていたが、決まった型を回す仕事が続いていた。`,
      (c) => `${c.beforeCompany}で${c.years}年目。社内の新規事業提案制度に応募した経験があり、そこで得た手応えが転職を考えるきっかけになった。`,
    ],
  }),
];
